// meals-library.js — 30 vanlige middager for småbarnsfamilie.
// Mengder er for 2 voksne + 2 barn (6 og 8 år) ≈ 3 voksenporsjoner.
export const MEAL_LIBRARY = [
  {n: 'Taco', cat: 'Tex-Mex', ing: [{n: 'Kjøttdeig', qty: 1}, {n: 'Tacolefser', qty: 2}, {n: 'Tacokrydder', qty: 1}, {n: 'Tacosaus', qty: 1}, {n: 'Mais', qty: 1}, {n: 'Agurk', qty: 1}, {n: 'Paprika', qty: 1}, {n: 'Tomater', qty: 2}, {n: 'Revet ost', qty: 1}, {n: 'Avokado', qty: 2}, {n: 'Tacoskjell', qty: 1}]},
  {n: 'Spagetti med kjøttsaus', cat: 'Pasta', ing: [{n: 'Kjøttdeig', qty: 1}, {n: 'Spagetti', qty: 1}, {n: 'Passata', qty: 1}, {n: 'Løk', qty: 1}, {n: 'Gulrøtter', qty: 2}, {n: 'Revet ost', qty: 1}]},
  {n: 'Lasagne', cat: 'Pasta', ing: [{n: 'Kjøttdeig', qty: 1}, {n: 'Lasagneplater', qty: 1}, {n: 'Passata', qty: 2}, {n: 'Hvit saus', qty: 1}, {n: 'Revet ost', qty: 1}, {n: 'Løk', qty: 1}]},
  {n: 'Ovnsbakt laks', cat: 'Fisk', ing: [{n: 'Laksefilet', qty: 2}, {n: 'Poteter', qty: 1}, {n: 'Brokkoli', qty: 1}, {n: 'Gulrøtter', qty: 3}, {n: 'Sitron', qty: 1}]},
  {n: 'Fiskekaker', cat: 'Fisk', ing: [{n: 'Fiskekaker', qty: 8}, {n: 'Poteter', qty: 1}, {n: 'Gulrøtter', qty: 3}, {n: 'Smør', qty: 1}]},
  {n: 'Fiskepinner', cat: 'Fisk', ing: [{n: 'Fiskepinner', qty: 12}, {n: 'Poteter', qty: 1}, {n: 'Erter', qty: 1}, {n: 'Remulade', qty: 1}]},
  {n: 'Panert sei', cat: 'Fisk', ing: [{n: 'Panert sei', qty: 4}, {n: 'Poteter', qty: 1}, {n: 'Gulrøtter', qty: 2}, {n: 'Agurk', qty: 1}]},
  {n: 'Hamburgere', cat: 'Grill', ing: [{n: 'Hamburgere', qty: 6}, {n: 'Burgerbrød', qty: 6}, {n: 'Burgerost', qty: 6}, {n: 'Salat', qty: 1}, {n: 'Tomater', qty: 2}, {n: 'Agurk', qty: 1}, {n: 'Dressing', qty: 1}]},
  {n: 'Pølser med lompe', cat: 'Grill', ing: [{n: 'Pølser', qty: 8}, {n: 'Lomper', qty: 1}, {n: 'Ketchup', qty: 1}, {n: 'Sprøstekt løk', qty: 1}]},
  {n: 'Hjemmelaget pizza', cat: 'Pizza', ing: [{n: 'Pizzabunn', qty: 2}, {n: 'Passata', qty: 1}, {n: 'Revet ost', qty: 2}, {n: 'Kokt skinke', qty: 1}, {n: 'Paprika', qty: 1}, {n: 'Mais', qty: 1}]},
  {n: 'Pizza fredag (frossen)', cat: 'Pizza', ing: [{n: 'Frossenpizza', qty: 2}, {n: 'Salat', qty: 1}, {n: 'Agurk', qty: 1}]},
  {n: 'Kylling curry', cat: 'Kylling', ing: [{n: 'Kyllingfilet', qty: 3}, {n: 'Ris', qty: 1}, {n: 'Currysaus', qty: 1}, {n: 'Paprika', qty: 1}, {n: 'Løk', qty: 1}, {n: 'Gryr fløte', qty: 1}]},
  {n: 'Kylling og ris', cat: 'Kylling', ing: [{n: 'Kyllingfilet', qty: 3}, {n: 'Ris', qty: 1}, {n: 'Brokkoli', qty: 1}, {n: 'Mais', qty: 1}, {n: 'Soyasaus', qty: 1}]},
  {n: 'Kyllingwok', cat: 'Kylling', ing: [{n: 'Kyllingfilet', qty: 3}, {n: 'Wokgrønnsaker', qty: 1}, {n: 'Nudler', qty: 2}, {n: 'Woksaus', qty: 1}]},
  {n: 'Kjøttkaker i brun saus', cat: 'Tradisjon', ing: [{n: 'Kjøttkaker', qty: 12}, {n: 'Poteter', qty: 1}, {n: 'Brun saus', qty: 1}, {n: 'Erter', qty: 1}, {n: 'Tyttebær', qty: 1}]},
  {n: 'Kjøttdeigsaus med ris', cat: 'Tradisjon', ing: [{n: 'Kjøttdeig', qty: 1}, {n: 'Ris', qty: 1}, {n: 'Løk', qty: 1}, {n: 'Passata', qty: 1}, {n: 'Mais', qty: 1}]},
  {n: 'Pannekaker', cat: 'Kos', ing: [{n: 'Hvetemel', qty: 1}, {n: 'Egg', qty: 6}, {n: 'Melk', qty: 1}, {n: 'Syltetøy', qty: 1}, {n: 'Bacon', qty: 1}]},
  {n: 'Tomatsuppe med makaroni', cat: 'Suppe', ing: [{n: 'Tomatsuppe', qty: 2}, {n: 'Makaroni', qty: 1}, {n: 'Egg', qty: 4}, {n: 'Brød', qty: 1}]},
  {n: 'Grønnsakssuppe', cat: 'Suppe', ing: [{n: 'Suppegrønnsaker', qty: 1}, {n: 'Buljong', qty: 2}, {n: 'Kjøttboller', qty: 1}, {n: 'Brød', qty: 1}]},
  {n: 'Fish and chips', cat: 'Fisk', ing: [{n: 'Panert torsk', qty: 4}, {n: 'Pommes frites', qty: 1}, {n: 'Erter', qty: 1}, {n: 'Remulade', qty: 1}]},
  {n: 'Omelett med skinke', cat: 'Rask', ing: [{n: 'Egg', qty: 8}, {n: 'Kokt skinke', qty: 1}, {n: 'Revet ost', qty: 1}, {n: 'Paprika', qty: 1}, {n: 'Brød', qty: 1}]},
  {n: 'Grøt (havregrøt/risgrøt)', cat: 'Kos', ing: [{n: 'Risgrøt', qty: 2}, {n: 'Sukker', qty: 1}, {n: 'Kanel', qty: 1}, {n: 'Smør', qty: 1}]},
  {n: 'Tortellini med pesto', cat: 'Pasta', ing: [{n: 'Tortellini', qty: 2}, {n: 'Pesto', qty: 1}, {n: 'Cherrytomater', qty: 1}, {n: 'Parmesan', qty: 1}]},
  {n: 'Wraps med kylling', cat: 'Rask', ing: [{n: 'Kyllingfilet', qty: 2}, {n: 'Tortilla', qty: 8}, {n: 'Salat', qty: 1}, {n: 'Mais', qty: 1}, {n: 'Rømme', qty: 1}, {n: 'Revet ost', qty: 1}]},
  {n: 'Pølsegryte', cat: 'Gryte', ing: [{n: 'Pølser', qty: 6}, {n: 'Makaroni', qty: 1}, {n: 'Passata', qty: 1}, {n: 'Paprika', qty: 1}, {n: 'Løk', qty: 1}]},
  {n: 'Chili con carne (mild)', cat: 'Gryte', ing: [{n: 'Kjøttdeig', qty: 1}, {n: 'Bønner i chilisaus', qty: 2}, {n: 'Ris', qty: 1}, {n: 'Mais', qty: 1}, {n: 'Rømme', qty: 1}]},
  {n: 'Makrell i tomat på brød', cat: 'Rask', ing: [{n: 'Makrell i tomat', qty: 2}, {n: 'Brød', qty: 1}, {n: 'Egg', qty: 4}, {n: 'Agurk', qty: 1}]},
  {n: 'Pytt i panne', cat: 'Rask', ing: [{n: 'Poteter', qty: 1}, {n: 'Pølser', qty: 4}, {n: 'Løk', qty: 1}, {n: 'Egg', qty: 4}, {n: 'Paprika', qty: 1}]},
  {n: 'Fiskeburger', cat: 'Fisk', ing: [{n: 'Fiskeburger', qty: 6}, {n: 'Burgerbrød', qty: 6}, {n: 'Salat', qty: 1}, {n: 'Remulade', qty: 1}, {n: 'Agurk', qty: 1}]},
  {n: 'Vegetarpasta', cat: 'Vegetar', ing: [{n: 'Pasta', qty: 1}, {n: 'Cherrytomater', qty: 1}, {n: 'Squash', qty: 1}, {n: 'Gryr fløte', qty: 1}, {n: 'Parmesan', qty: 1}, {n: 'Hvitløk', qty: 1}]}
];
