-- AUTOGENERERT av scripts/generate-recipe-sources-sql.mjs — ikke rediger for hånd.
-- Kanonisk kilde: src/lib/recipes/sources.js (17 kilder).

insert into public.recipe_sources
  (id, name, base_url, country, language, priority, integration_modes, enabled,
   can_discover, can_fetch_recipe, can_store_metadata, can_store_ingredients,
   can_store_instructions, can_store_images, requires_attribution,
   terms_status, robots_status, sample_urls, notes)
values
  ('rema', 'REMA 1000', 'https://www.rema.no', 'NO', 'nb', 80, array['STRUCTURED_DATA', 'SITEMAP_DISCOVERY', 'HTML_RECIPE', 'LINK_DISCOVERY_ONLY']::text[], true, true, true, true, true, false, false, true, 'unreviewed', 'unknown', array['https://www.rema.no/oppskrifter/middagstips/']::text[], 'Rike kildekategorier (råvare/måltid/anledning/sesong/retttype/kjøkken) — mappes til vår taksonomi, aldri adoptert rått.'),
  ('tine', 'TINE', 'https://www.tine.no', 'NO', 'nb', 80, array['STRUCTURED_DATA', 'SITEMAP_DISCOVERY', 'HTML_RECIPE', 'LINK_DISCOVERY_ONLY']::text[], true, true, true, true, true, false, false, true, 'unreviewed', 'unknown', array['https://www.tine.no/oppskrifter/tema/middag']::text[], 'Gjennomgående eksplisitte porsjoner og tid («6 personer / 50 min») — prioriter oppskrifter med servings_confidence=high.'),
  ('matprat', 'MatPrat', 'https://www.matprat.no', 'NO', 'nb', 80, array['DISABLED_PENDING_PERMISSION', 'LINK_DISCOVERY_ONLY']::text[], false, true, false, true, false, false, false, true, 'unreviewed', 'unknown', array['https://www.matprat.no/artikler/middagstips/']::text[], 'EKSPLISITT BEGRENSNING: MatPrat tilbyr ikke tredjeparts-API og tillater ikke uttrekk av oppskriftsbasen uten avtale. Kun lenking og manuell flagging til avtale ev. foreligger.'),
  ('meny', 'MENY', 'https://meny.no', 'NO', 'nb', 80, array['STRUCTURED_DATA', 'SITEMAP_DISCOVERY', 'HTML_RECIPE', 'LINK_DISCOVERY_ONLY']::text[], true, true, true, true, true, false, false, true, 'unreviewed', 'unknown', array['https://meny.no/oppskrifter/middagstips']::text[], 'Stor oppdagelseskilde. Bruk listesider til oppdaging; hent detaljer kun ved behov — aldri bulk fordi det er mulig.'),
  ('kiwi', 'KIWI', 'https://kiwi.no', 'NO', 'nb', 80, array['STRUCTURED_DATA', 'SITEMAP_DISCOVERY', 'HTML_RECIPE', 'LINK_DISCOVERY_ONLY']::text[], true, true, true, true, true, false, false, true, 'unreviewed', 'unknown', array['https://kiwi.no/billig-middag', 'https://kiwi.no/oppskrifter']::text[], 'Inspirasjon + fremtidig tilbudskontekst. En KIWI-oppskrift binder ALDRI handelen til KIWI — husholdningen kan kjøpe alt på Coop Extra.'),
  ('coop', 'Coop', 'https://www.coop.no', 'NO', 'nb', 80, array['STRUCTURED_DATA', 'SITEMAP_DISCOVERY', 'HTML_RECIPE', 'LINK_DISCOVERY_ONLY']::text[], true, true, true, true, true, false, false, true, 'unreviewed', 'unknown', array['https://www.coop.no/inspirasjon/middag', 'https://www.coop.no/oppskrifter']::text[], 'Filtre (nasjonalitet/hovedråvare/type/sesong/tid/vanskelighet) mappes til vår taksonomi. «Kjøttdeig» i oppskrift er ingrediens; «Xtra kjøttdeig» er produktvalg — hold begrepene adskilt.'),
  ('oda', 'Oda', 'https://oda.com', 'NO', 'nb', 80, array['STRUCTURED_DATA', 'PUBLIC_JSON', 'HTML_RECIPE', 'LINK_DISCOVERY_ONLY']::text[], true, true, true, true, true, false, false, true, 'unreviewed', 'unknown', array['https://oda.com/no/about/middagstips/', 'https://oda.com/no/recipes/']::text[], 'Modellen deres (oppskrift→porsjoner→ingredienser→varer) er den vi vil speile — men i VÅRT Item/Kassalapp-system. Lagre aldri Odas handlekurv.'),
  ('gilde', 'Gilde', 'https://www.gilde.no', 'NO', 'nb', 80, array['STRUCTURED_DATA', 'SITEMAP_DISCOVERY', 'HTML_RECIPE', 'LINK_DISCOVERY_ONLY']::text[], true, true, true, true, true, false, false, true, 'unreviewed', 'unknown', array['https://www.gilde.no/konsept/middagstips', 'https://www.gilde.no/oppskrifter']::text[], 'Kjøttbasert og tradisjonsmat. «Kvernet storfekjøtt» hardbindes aldri til Gilde-produkt — produktmatchingen velger etter preferanse og pris.'),
  ('frukt', 'FRUKT.no', 'https://www.frukt.no', 'NO', 'nb', 80, array['STRUCTURED_DATA', 'SITEMAP_DISCOVERY', 'HTML_RECIPE', 'LINK_DISCOVERY_ONLY']::text[], true, true, true, true, true, false, false, true, 'unreviewed', 'unknown', array['https://www.frukt.no/tema/middag/']::text[], 'Positivt signal når vi vil ha mer grønnsaker, familievennlig, billig eller rask hverdag — kildetags (Rask/Billig/Sunn/Familievennlig) går rett i scoringen.'),
  ('trines', 'Trines Matblogg', 'https://trinesmatblogg.no', 'NO', 'nb', 80, array['STRUCTURED_DATA', 'RSS_DISCOVERY', 'URL_IMPORT', 'LINK_DISCOVERY_ONLY']::text[], true, true, true, true, true, false, false, true, 'unreviewed', 'unknown', array['https://trinesmatblogg.no/category/middag/']::text[], 'Blogg: JSON-LD → RSS → enkelt-URL-import → lenk ut. Aldri aggressiv kravling.'),
  ('detgladekjokken', 'Det Glade Kjøkken', 'https://detgladekjokken.no', 'NO', 'nb', 80, array['STRUCTURED_DATA', 'RSS_DISCOVERY', 'URL_IMPORT', 'LINK_DISCOVERY_ONLY']::text[], true, true, true, true, true, false, false, true, 'unreviewed', 'unknown', array['https://detgladekjokken.no/middagstips/']::text[], 'Blogg — samme varsomme modell som Trines.'),
  ('lindastuhaug', 'Linda Stuhaug', 'https://lindastuhaug.no', 'NO', 'nb', 80, array['STRUCTURED_DATA', 'RSS_DISCOVERY', 'URL_IMPORT', 'LINK_DISCOVERY_ONLY']::text[], true, true, true, true, true, false, false, true, 'unreviewed', 'unknown', array['https://lindastuhaug.no/']::text[], '«Ukens fisk/kjøtt/vegetar» kan brukes som oppdagelsesfeed og inspirere vår egen ukesbalanse.'),
  ('idamariesmat', 'Ida Maries Mat', 'https://idamariesmat.no', 'NO', 'nb', 80, array['STRUCTURED_DATA', 'RSS_DISCOVERY', 'URL_IMPORT', 'LINK_DISCOVERY_ONLY']::text[], true, true, true, true, true, false, false, true, 'unreviewed', 'unknown', array['https://idamariesmat.no/tag/middagstips/']::text[], 'Blogg — samme varsomme modell som Trines.'),
  ('edamam', 'Edamam', 'https://api.edamam.com', 'INT', 'en', 40, array['API']::text[], false, true, true, true, true, false, false, true, 'plan_restricted', 'n/a', array[]::text[], 'Høyvolums SØK/OPPDAGING. Persister aldri fulle oppskrifter — lagre ekstern id + kilde-URL, hent etter planens bruksmodell. Secrets: EDAMAM_APP_ID, EDAMAM_APP_KEY.'),
  ('api_ninjas', 'API Ninjas Recipe', 'https://api.api-ninjas.com', 'INT', 'en', 40, array['API']::text[], false, true, true, true, true, false, false, true, 'plan_restricted', 'n/a', array[]::text[], 'Strukturerte ingredienser (navn/mengde/enhet). Premium-søk deaktiveres pent når kontoen ikke støtter det. Secret: API_NINJAS_KEY.'),
  ('recipe_api', 'Recipe API', 'https://api.recipeapi.dev', 'INT', 'en', 40, array['API']::text[], false, true, true, true, true, false, false, true, 'plan_restricted', 'n/a', array[]::text[], 'Kvalitet framfor volum: yield_count brukes direkte som base_servings. Respekter planens cache-regler — persister aldri lenger enn planen tillater. Secret: RECIPE_API_KEY.'),
  ('themealdb', 'TheMealDB', 'https://www.themealdb.com', 'INT', 'en', 40, array['API']::text[], true, true, true, true, true, false, false, true, 'free_dev', 'n/a', array['https://www.themealdb.com/api/json/v1/1/search.php?s=salmon']::text[], 'Liten katalog — utvikling, kjøkkenoppdaging og tilfeldig inspirasjon. Aldri hovedarkivet.')
on conflict (id) do update set
  name = excluded.name,
  base_url = excluded.base_url,
  priority = excluded.priority,
  integration_modes = excluded.integration_modes,
  sample_urls = excluded.sample_urls,
  notes = excluded.notes;
-- enabled/can_*-flagg oppdateres BEVISST ikke ved konflikt: en manuell
-- innstramming i databasen skal ikke reverseres av en ny deploy.
