-- AUTOGENERERT av scripts/generate-seed.mjs — ikke rediger for hånd.
-- Kilde: 51 kvitteringer, 632 varelinjer (Coop Extra + MENY + REMA 1000 (mar–aug 2026)).
-- Oppdatert: 2026-08-27

-- Butikker
insert into public.stores (code, name, store_type, is_default, sort_order) values
  ('COOP_EXTRA', 'Coop Extra', 'lavpris', true, 10),
  ('MENY_NO', 'Meny', 'fullsortiment', false, 20),
  ('REMA_1000', 'Rema 1000', 'lavpris', false, 30),
  ('KIWI', 'KIWI', 'lavpris', false, 40),
  ('COOP_OBS', 'Coop Obs', 'hypermarked', false, 50),
  ('SPAR_NO', 'Spar', 'nærbutikk', false, 60),
  ('JOKER', 'Joker', 'nærbutikk', false, 70);

-- Varekatalog: 465 varer
insert into public.item_catalog
  (name, name_en, category, major_category, is_food, line_count, receipt_count,
   avg_price, price_low, price_high, frequency_sig, primary_store, store_dist, score, brand)
values
  ('Brød/bakervarer', 'Bread/baked goods', 'Brød og bakervarer', 'Brød og korn', true, 24, 19, 57, 17, 180, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 12; MENY: 8; REMA 1000: 3; Coop Extra Hovden: 1', 93, NULL),
  ('Paprika', 'Bell pepper', 'Frukt og grønt', 'Frukt og grønt', true, 18, 16, 30, 16, 55, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 14; MENY: 2; Coop Extra: 1; REMA 1000: 1', 78, NULL),
  ('Brus/kullsyrevann/øl', 'Soda/sparkling water/beer', 'Drikke', 'Drikke', true, 25, 15, 93, 26, 227, NULL, 'Meny', 'MENY: 11; REMA 1000: 6; Coop Extra Dr. Munk: 5; Coop Extra Hovden: 2; Coop Extra: 1', 70, NULL),
  ('Poteter', 'Potatoes', 'Frukt og grønt', 'Frukt og grønt', true, 17, 12, 48, 14, 99, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 11; MENY: 3; REMA 1000: 3', 65, NULL),
  ('Agurk', 'Cucumber', 'Frukt og grønt', 'Frukt og grønt', true, 14, 11, 57, 23, 112, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 13; Coop Extra Hovden: 1', 59, NULL),
  ('Tomater/passata/tomatboks', 'Tomatoes/passata/canned tomatoes', 'Tørrvarer', 'Tørrvarer', true, 14, 11, 37, 15, 56, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 12; MENY: 1; REMA 1000: 1', 59, NULL),
  ('Jordbær', 'Strawberries', 'Frukt og grønt', 'Frukt og grønt', true, 11, 11, 60, 25, 100, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 8; MENY: 3', 56, NULL),
  ('Løk', 'Onion', 'Frukt og grønt', 'Frukt og grønt', true, 12, 9, 25, 12, 47, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 8; MENY: 3; Coop Extra: 1', 51, NULL),
  ('Ris', 'Rice', 'Tørrvarer', 'Tørrvarer', true, 11, 9, 54, 24, 87, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 7; MENY: 2; REMA 1000: 2', 50, NULL),
  ('Kjøttdeig/karbonadedeig', 'Minced meat', 'Kjøtt', 'Kjøtt', true, 9, 8, 198, 79, 280, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 4; MENY: 2; REMA 1000: 2; Coop Extra: 1', 45, NULL),
  ('Cottage cheese', 'Cottage cheese', 'Meieri', 'Meieri', true, 8, 8, 59, 47, 96, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 7; MENY: 1', 44, NULL),
  ('Melk', 'Milk', 'Meieri', 'Meieri', true, 8, 8, 35, 22, 50, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 3; MENY: 3; REMA 1000: 2', 44, NULL),
  ('Makrell i tomat', 'Mackerel in tomato', 'Pålegg', 'Ost og pålegg', true, 14, 6, 55, 20, 125, 'Svært ofte', 'Rema 1000', 'REMA 1000: 9; Coop Extra Dr. Munk: 5', 44, NULL),
  ('Tacolefser/tortilla/lomper', 'Tortillas/flatbread', 'Taco/Tex-Mex', 'Tørrvarer', true, 13, 10, 27, 0, 132, NULL, 'Rema 1000', 'REMA 1000: 5; Coop Extra Dr. Munk: 3; MENY: 3; Coop Extra Hovden: 1; Coop Extra: 1', 43, NULL),
  ('Gryr matfløte / plantedrikk', 'Plant-based cream/drink', 'Melkefritt/plantebasert', 'Meieri', true, 9, 7, 55, 26, 104, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 5; REMA 1000: 3; MENY: 1', 42, NULL),
  ('Gulost/Norvegia', 'Yellow cheese', 'Meieri', 'Meieri', true, 9, 7, 226, 61, 664, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 7; MENY: 2', 42, NULL),
  ('Kylling', 'Chicken', 'Kjøtt', 'Kjøtt', true, 9, 7, 131, 34, 254, 'Svært ofte', 'Meny', 'MENY: 5; Coop Extra Dr. Munk: 2; REMA 1000: 2', 42, NULL),
  ('Knekkebrød/Rugsprø', 'Crispbread', 'Brød og bakervarer', 'Brød og korn', true, 8, 7, 42, 15, 65, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 7; MENY: 1', 41, NULL),
  ('Pasta/spagetti/lasagneplater', 'Pasta/spaghetti/lasagne sheets', 'Tørrvarer', 'Tørrvarer', true, 8, 6, 53, 13, 120, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 8', 38, NULL),
  ('Rømme/crème fraîche', 'Sour cream / crème fraîche', 'Meieri', 'Meieri', true, 10, 9, 39, 22, 72, NULL, 'Meny', 'MENY: 4; REMA 1000: 4; Coop Extra Dr. Munk: 2', 37, NULL),
  ('Saus/grytepose', 'Sauce/stew mix', 'Sauser/tilbehør', 'Krydder og saus', true, 7, 6, 50, 29, 82, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 7', 37, NULL),
  ('Brokkoli', 'Broccoli', 'Frukt og grønt', 'Frukt og grønt', true, 6, 6, 24, 9, 45, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 6', 36, NULL),
  ('Gulrøtter', 'Carrots', 'Frukt og grønt', 'Frukt og grønt', true, 6, 6, 27, 10, 48, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 6', 36, NULL),
  ('Mais', 'Corn', 'Taco/Tex-Mex', 'Tørrvarer', true, 6, 6, 51, 27, 100, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 4; MENY: 1; REMA 1000: 1', 36, NULL),
  ('Potetgull/chips', 'Potato chips/crisps', 'Snacks/godteri', 'Snacks', true, 8, 5, 19, 10, 39, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 3; Coop Extra: 3; MENY: 1; REMA 1000: 1', 35, NULL),
  ('Grillkjøtt/koteletter/ribs', 'Grill meat/cutlets/ribs', 'Kjøtt', 'Kjøtt', true, 9, 4, 128, 38, 219, 'Svært ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 8; MENY: 1', 33, NULL),
  ('Soyamelk uten sukker', 'Unsweetened soy milk', 'Melkefritt/plantebasert', 'Meieri', true, 7, 5, 50, 30, 90, 'Ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 4; REMA 1000: 3', 31, NULL),
  ('Burgerbrød', 'Burger buns', 'Brød og bakervarer', 'Brød og korn', true, 6, 5, 29, 23, 46, 'Ofte', 'Rema 1000', 'REMA 1000: 4; Coop Extra Dr. Munk: 2', 30, NULL),
  ('Epler', 'Apples', 'Frukt og grønt', 'Frukt og grønt', true, 6, 5, 43, 25, 60, 'Ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 4; MENY: 2', 30, NULL),
  ('Ketchup', 'Ketchup', 'Sauser/tilbehør', 'Krydder og saus', true, 5, 5, 52, 34, 61, 'Ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 4; Coop Extra: 1', 29, NULL),
  ('Tine Lettrom.17%300G', 'Tine Lettrom.17%300G', 'Ukjent/ikke klassifisert', 'Annet', true, 5, 5, 33, 23, 48, 'Ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 4; Coop Extra: 1', 29, NULL),
  ('Plastpose', 'Plastpose', 'Non-food/household', 'Hus og hjem', false, 5, 5, 8, 7, 14, 'Ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 4; Coop Extra Hovden: 1', 29, NULL),
  ('Mozzarella', 'Mozzarella', 'Meieri', 'Meieri', true, 6, 4, 42, 30, 66, 'Ofte', 'Rema 1000', 'REMA 1000: 3; Coop Extra Dr. Munk: 2; MENY: 1', 27, NULL),
  ('Is', 'Ice cream', 'Snacks/godteri', 'Snacks', true, 8, 6, 67, 25, 86, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 5; MENY: 3', 26, NULL),
  ('Yoghurt', 'Yogurt', 'Meieri', 'Meieri', true, 8, 6, 46, 20, 94, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 6; MENY: 2', 26, NULL),
  ('Pølser', 'Sausages', 'Kjøtt', 'Kjøtt', true, 7, 6, 79, 52, 99, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 4; MENY: 2; REMA 1000: 1', 25, NULL),
  ('Coop Ha.Tom.Urt.390G', 'Coop Ha.Tom.Urt.390G', 'Ukjent/ikke klassifisert', 'Annet', true, 4, 4, 29, 26, 30, 'Ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 4', 25, NULL),
  ('Egg', 'Eggs', 'Egg', 'Meieri', true, 4, 4, 65, 40, 80, 'Ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 3; MENY: 1', 25, NULL),
  ('Kalkun/kalkunpølse', 'Turkey/turkey sausage', 'Kjøtt', 'Kjøtt', true, 4, 4, 257, 51, 797, 'Ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 2; MENY: 2', 25, NULL),
  ('Sjokolade/godteri', 'Chocolate/candy', 'Snacks/godteri', 'Snacks', true, 4, 4, 48, 38, 57, 'Ofte', 'Meny', 'MENY: 2; Coop Extra Dr. Munk: 1; REMA 1000: 1', 25, NULL),
  ('Tortillachips/nachos', 'Tortilla chips/nachos', 'Taco/Tex-Mex', 'Tørrvarer', true, 4, 4, 42, 38, 45, 'Ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 2; MENY: 2', 25, NULL),
  ('Sjokoladepålegg', 'Chocolate spread', 'Pålegg', 'Ost og pålegg', true, 6, 6, 39, 37, 40, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 4; Coop Extra: 1; REMA 1000: 1', 24, NULL),
  ('Hamburgere/burgerost', 'Burgers/burger cheese', 'Kjøtt', 'Kjøtt', true, 9, 5, 93, 34, 150, NULL, 'Rema 1000', 'REMA 1000: 6; Coop Extra Dr. Munk: 3', 24, NULL),
  ('Bacon', 'Bacon', 'Kjøtt', 'Kjøtt', true, 4, 3, 64, 32, 128, 'Ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 2; REMA 1000: 2', 22, NULL),
  ('Feta/salatost', 'Feta/salad cheese', 'Meieri', 'Meieri', true, 3, 3, 42, 30, 64, 'Ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 3', 21, NULL),
  ('Kiwi', 'Kiwi fruit', 'Frukt og grønt', 'Frukt og grønt', true, 3, 3, 70, 40, 119, 'Ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 2; MENY: 1', 21, NULL),
  ('Laks', 'Salmon', 'Fisk', 'Fisk', true, 3, 3, 144, 93, 190, 'Ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 3', 21, NULL),
  ('Lime', 'Lime', 'Frukt og grønt', 'Frukt og grønt', true, 3, 3, 6, 4, 8, 'Ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 2; Coop Extra: 1', 21, NULL),
  ('Salat', 'Salad', 'Frukt og grønt', 'Frukt og grønt', true, 3, 3, 51, 27, 90, 'Ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 2; Coop Extra Hovden: 1', 21, NULL),
  ('Gril Jubelsalam.250G', 'Gril Jubelsalam.250G', 'Ukjent/ikke klassifisert', 'Annet', true, 5, 5, 79, 60, 90, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 4; Coop Extra: 1', 20, NULL),
  ('Isbergsalat', 'Iceberg lettuce', 'Frukt og grønt', 'Frukt og grønt', true, 5, 5, 24, 15, 37, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 2; Coop Extra: 1; MENY: 1; REMA 1000: 1', 20, NULL),
  ('Tacosaus/salsa', 'Taco sauce/salsa', 'Taco/Tex-Mex', 'Tørrvarer', true, 5, 5, 23, 20, 30, NULL, 'Meny', 'MENY: 2; Coop Extra Dr. Munk: 1; Coop Extra: 1; REMA 1000: 1', 20, NULL),
  ('Tine Lettm.0.5%1.75L', 'Tine Lettm.0.5%1.75L', 'Ukjent/ikke klassifisert', 'Annet', true, 5, 5, 31, 30, 34, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 5', 20, NULL),
  ('Buljong', 'Bouillon/stock', 'Tørrvarer', 'Tørrvarer', true, 5, 2, 31, 18, 36, 'Ofte', 'Coop Extra', 'Coop Extra Dr. Munk: 5', 20, NULL),
  ('Bzereposer 80 %', 'Bzereposer 80 %', 'Non-food/household', 'Hus og hjem', false, 5, 5, 7, 7, 7, NULL, 'Rema 1000', 'REMA 1000: 5', 20, NULL),
  ('Dressing/salater/tilbehør', 'Dressing/salads/condiments', 'Sauser/tilbehør', 'Krydder og saus', true, 4, 4, 35, 20, 51, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 2; REMA 1000: 2', 16, NULL),
  ('Havremelk', 'Oat milk', 'Melkefritt/plantebasert', 'Meieri', true, 4, 4, 58, 35, 80, NULL, 'Meny', 'MENY: 3; Coop Extra Dr. Munk: 1', 16, NULL),
  ('Revet ost', 'Grated cheese', 'Meieri', 'Meieri', true, 4, 4, 77, 60, 120, NULL, 'Meny', 'MENY: 2; Coop Extra Dr. Munk: 1; REMA 1000: 1', 16, NULL),
  ('Smeremyk 600G Eldorado', 'Smeremyk 600G Eldorado', 'Ukjent/ikke klassifisert', 'Annet', true, 4, 4, 127, 82, 180, NULL, 'Meny', 'MENY: 4', 16, NULL),
  ('Tex-Mex kit', 'Tex-Mex kit', 'Taco/Tex-Mex', 'Tørrvarer', true, 4, 4, 50, 40, 73, NULL, 'Meny', 'MENY: 2; Coop Extra Dr. Munk: 1; REMA 1000: 1', 16, NULL),
  ('Bananer', 'Bananas', 'Frukt og grønt', 'Frukt og grønt', true, 2, 2, 28, 24, 32, 'Av og til', 'Coop Extra', 'Coop Extra Hovden: 1; Coop Extra Dr. Munk: 1', 14, NULL),
  ('Blomkål', 'Cauliflower', 'Frukt og grønt', 'Frukt og grønt', true, 2, 2, 70, 60, 80, 'Av og til', 'Coop Extra', 'Coop Extra Dr. Munk: 2', 14, NULL),
  ('Gril Jubelsalam.170G', 'Gril Jubelsalam.170G', 'Ukjent/ikke klassifisert', 'Annet', true, 2, 2, 120, 116, 124, 'Av og til', 'Coop Extra', 'Coop Extra Dr. Munk: 2', 14, NULL),
  ('Pærer', 'Pears', 'Frukt og grønt', 'Frukt og grønt', true, 2, 2, 47, 43, 51, 'Av og til', 'Coop Extra', 'Coop Extra Dr. Munk: 2', 14, NULL),
  ('Rødspette', 'Plaice', 'Fisk', 'Fisk', true, 2, 2, 151, 101, 202, 'Av og til', 'Coop Extra', 'Coop Extra Dr. Munk: 2', 14, NULL),
  ('Tub.Lite 0.5L Bx', 'Tub.Lite 0.5L Bx', 'Ukjent/ikke klassifisert', 'Annet', true, 2, 2, 96, 64, 128, 'Av og til', 'Coop Extra', 'Coop Extra Dr. Munk: 1; Coop Extra: 1', 14, NULL),
  ('Salami/spekeskinke', 'Salami/cured ham', 'Pålegg', 'Ost og pålegg', true, 4, 3, 64, 38, 80, NULL, 'Rema 1000', 'REMA 1000: 3; Coop Extra Dr. Munk: 1', 13, NULL),
  ('Blåbær', 'Blueberries', 'Frukt og grønt', 'Frukt og grønt', true, 3, 3, 46, 39, 60, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 2; MENY: 1', 12, NULL),
  ('Extra White Sweetmint 84G Boks', 'Extra White Sweetmint 84G Boks', 'Ukjent/ikke klassifisert', 'Annet', true, 3, 3, 66, 65, 66, NULL, 'Meny', 'MENY: 3', 12, NULL),
  ('Kjeks/snacks', 'Biscuits/snacks', 'Snacks/godteri', 'Snacks', true, 3, 3, 57, 37, 73, NULL, 'Meny', 'MENY: 2; REMA 1000: 1', 12, NULL),
  ('Kokt skinke', 'Cooked ham', 'Pålegg', 'Ost og pålegg', true, 3, 3, 40, 20, 66, NULL, 'Meny', 'MENY: 2; REMA 1000: 1', 12, NULL),
  ('Nøtter/peanøtter', 'Nuts/peanuts', 'Snacks/godteri', 'Snacks', true, 3, 3, 39, 27, 55, NULL, 'Coop Extra', 'Coop Extra Hovden: 1; Coop Extra Dr. Munk: 1; MENY: 1', 12, NULL),
  ('Tub.Lite 0.5L Bx 6Pk', 'Tub.Lite 0.5L Bx 6Pk', 'Ukjent/ikke klassifisert', 'Annet', true, 3, 3, 197, 191, 200, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 3', 12, NULL),
  ('Lambi Toa.Papir 24Pk', 'Lambi Toa.Papir 24Pk', 'Non-food/household', 'Hus og hjem', false, 3, 3, 129, 99, 144, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 3', 12, NULL),
  ('Gjenbruk Handlenett', 'Gjenbruk Handlenett', 'Non-food/household', 'Hus og hjem', false, 3, 2, 0, 0, 0, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 3', 9, NULL),
  ('Avokado', 'Avocado', 'Frukt og grønt', 'Frukt og grønt', true, 2, 2, 36, 30, 43, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1; Coop Extra: 1', 8, NULL),
  ('Coop Micropopc.Smor', 'Coop Micropopc.Smor', 'Ukjent/ikke klassifisert', 'Annet', true, 2, 2, 19, 17, 21, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 2', 8, NULL),
  ('Gjær/bakepulver', 'Yeast/baking powder', 'Baking', 'Tørrvarer', true, 2, 2, 26, 19, 33, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1; REMA 1000: 1', 8, NULL),
  ('Krydder/urter', 'Spices/herbs', 'Krydder', 'Krydder og saus', true, 2, 2, 19, 19, 19, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 2', 8, NULL),
  ('Leverpostei', 'Liver pâté', 'Pålegg', 'Ost og pålegg', true, 2, 2, 15, 15, 15, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 2', 8, NULL),
  ('Mel', 'Flour', 'Baking', 'Tørrvarer', true, 2, 2, 23, 19, 27, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 2', 8, NULL),
  ('Melkefri/plantebasert yoghurt eller is', 'Dairy-free/plant-based yogurt or ice cream', 'Melkefritt/plantebasert', 'Meieri', true, 2, 2, 59, 50, 69, NULL, 'Meny', 'MENY: 2', 8, NULL),
  ('Oboy/kakao', 'Chocolate milk powder/cocoa', 'Drikke', 'Drikke', true, 2, 2, 85, 62, 108, NULL, 'Coop Extra', 'Coop Extra Hovden: 1; MENY: 1', 8, NULL),
  ('Ruccola', 'Arugula', 'Frukt og grønt', 'Frukt og grønt', true, 2, 2, 15, 15, 15, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1; MENY: 1', 8, NULL),
  ('Sennep', 'Mustard', 'Sauser/tilbehør', 'Krydder og saus', true, 2, 2, 27, 24, 30, NULL, 'Meny', 'MENY: 1; REMA 1000: 1', 8, NULL),
  ('Smaégodt Pr Kg', 'Smaégodt Pr Kg', 'Ukjent/ikke klassifisert', 'Annet', true, 2, 2, 78, 63, 93, NULL, 'Meny', 'MENY: 2', 8, NULL),
  ('Sukker/melis', 'Sugar/icing sugar', 'Baking', 'Tørrvarer', true, 2, 2, 24, 13, 35, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1; MENY: 1', 8, NULL),
  ('Tacokrydder', 'Taco seasoning', 'Taco/Tex-Mex', 'Tørrvarer', true, 2, 2, 23, 23, 24, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1; Coop Extra: 1', 8, NULL),
  ('Varrull M/Kylling Varm Pr Stk', 'Varrull M/Kylling Varm Pr Stk', 'Ukjent/ikke klassifisert', 'Annet', true, 2, 2, 80, 80, 80, NULL, 'Meny', 'MENY: 2', 8, NULL),
  ('Xtra Kokt Skink.250G', 'Xtra Kokt Skink.250G', 'Ukjent/ikke klassifisert', 'Annet', true, 2, 2, 35, 34, 35, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 2', 8, NULL),
  ('Bzrepose Papir Meny 26] 32X17X40 Cm', 'Bzrepose Papir Meny 26] 32X17X40 Cm', 'Non-food/household', 'Hus og hjem', false, 2, 2, 7, 5, 9, NULL, 'Meny', 'MENY: 2', 8, NULL),
  ('24 Smoot.Bendit', '24 Smoot.Bendit', 'Ukjent/ikke klassifisert', 'Annet', true, 2, 1, 15, 15, 15, NULL, 'Rema 1000', 'REMA 1000: 2', 5, NULL),
  ('Lice Nicesourcreaam&', 'Lice Nicesourcreaam&', 'Ukjent/ikke klassifisert', 'Annet', true, 2, 1, 20, 20, 20, NULL, 'Rema 1000', 'REMA 1000: 2', 5, NULL),
  ('Popcorn', 'Popcorn', 'Snacks/godteri', 'Snacks', true, 2, 1, 22, 19, 26, NULL, 'Meny', 'MENY: 2', 5, NULL),
  ('Sei', 'Saithe', 'Fisk', 'Fisk', true, 2, 1, 33, 29, 37, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 2', 5, NULL),
  ('Thick&Juicy Big', 'Thick&Juicy Big', 'Ukjent/ikke klassifisert', 'Annet', true, 2, 1, 50, 50, 50, NULL, 'Rema 1000', 'REMA 1000: 2', 5, NULL),
  ('Gulost', 'Yellow cheese, Norvegia', 'Ost', 'Ost og pålegg', true, 0, 0, 110, 0, 0, NULL, NULL, NULL, 5, 'Norvegia Duopack; Tine økonomipakke'),
  ('Nugatti', 'Chocolate spread, Nugatti', 'Pålegg', 'Ost og pålegg', true, 0, 0, 39, 0, 0, NULL, NULL, NULL, 5, '500 g'),
  ('Rugsprø', 'Rye crispbread', 'Knekkebrød', 'Brød og korn', true, 0, 0, 10, 0, 0, NULL, NULL, NULL, 5, 'Wasa'),
  ('Salami', 'Salami', 'Pålegg', 'Ost og pålegg', true, 0, 0, 62, 0, 0, NULL, NULL, NULL, 5, 'Grilstad Jubelsalami; Taga trøffelsalami'),
  ('Brød', 'Bread', 'Brød og korn', 'Brød og korn', true, 0, 0, 51, 0, 0, NULL, NULL, NULL, 5, 'Coop Superbrød 750 g; Coop Havregullbrød'),
  ('Bretagne saus', 'Bretagne sauce', 'Saus/tilbehør', 'Krydder og saus', true, 0, 0, 26, 0, 0, NULL, NULL, NULL, 5, 'Toro familiepakke'),
  ('Gryr fløte', 'Plant-based cooking cream', 'Melkefritt', 'Meieri', true, 0, 0, 26, 0, 0, NULL, NULL, NULL, 5, 'Gryr kokos/raps'),
  ('Hakkede tomater med hvitløk', 'Chopped tomatoes with garlic', 'Hermetisk/tomat', 'Tørrvarer', true, 0, 0, 13, 0, 0, NULL, NULL, NULL, 5, 'Coop'),
  ('Hakkede tomater med urter', 'Chopped tomatoes with herbs', 'Hermetisk/tomat', 'Tørrvarer', true, 0, 0, 13, 0, 0, NULL, NULL, NULL, 5, 'Coop'),
  ('Jordbærsyltetøy', 'Strawberry jam, Skweezy', 'Syltetøy', 'Ost og pålegg', true, 0, 0, 30, 0, 0, NULL, NULL, NULL, 5, 'Nora; Coop 500 g'),
  ('Kjøttdeig', 'Minced meat', 'Kjøtt', 'Kjøtt', true, 0, 0, 70, 0, 0, NULL, NULL, NULL, 5, 'Xtra'),
  ('Krone-is', 'Ice cream cone', 'Is/dessert', 'Frysevarer', true, 0, 0, 78, 0, 0, NULL, NULL, NULL, 5, 'Coop / Cookie Dough / jordbær / sjokolade'),
  ('Kyllingbuljong', 'Chicken stock cubes', 'Buljong', 'Tørrvarer', true, 0, 0, 18, 0, 0, NULL, NULL, NULL, 5, 'Maggi'),
  ('Lasagneplater', 'Lasagne sheets, Barilla', 'Pasta', 'Tørrvarer', true, 0, 0, 42, 0, 0, NULL, NULL, NULL, 5, 'Barilla'),
  ('Lettmelk', 'Low-fat milk', 'Meieri', 'Meieri', true, 0, 0, 30, 0, 0, NULL, NULL, NULL, 5, 'Tine 0,5% 1,75 L; Q-Meieriene 0,5% 1,75 L'),
  ('Lettrømme', 'Light sour cream', 'Meieri', 'Meieri', true, 0, 0, 24, 0, 0, NULL, NULL, NULL, 5, 'Tine 17% 300 g'),
  ('Pizzabunn', 'Pizza base', 'Pizza', 'Frysevarer', true, 0, 0, 32, 0, 0, NULL, NULL, NULL, 5, 'Peppes; Q/QD 2-pk'),
  ('Potetsalat', 'Potato salad', 'Tilbehør/grill', 'Tørrvarer', true, 0, 0, 29, 0, 0, NULL, NULL, NULL, 5, 'Coop/Klassisk'),
  ('Ãm Tomater Finmost', 'Ãm Tomater Finmost', 'Ukjent', 'Annet', true, 0, 0, 28, 0, 0, NULL, NULL, NULL, 5, NULL),
  ('Øl', 'Beer', 'Drikke/voksen', 'Drikke', true, 0, 0, 32, 0, 0, NULL, NULL, NULL, 5, 'Tuborg Lite'),
  ('Toalettpapir', 'Toilet paper', 'Husholdning', 'Hus og hjem', true, 0, 0, 144, 0, 0, NULL, NULL, NULL, 5, 'Lambi 24-pk'),
  ('Fullkornsspagetti', 'Whole wheat spaghetti', 'Pasta', 'Tørrvarer', true, 0, 0, 58, 0, 0, NULL, NULL, NULL, 5, 'Barilla'),
  ('Hamburgere', 'Hamburgers / burger patties', 'Kjøtt/burger', 'Kjøtt', true, 0, 0, 150, 0, 0, NULL, NULL, NULL, 5, 'Gilde 800 g'),
  ('Kyllingfilet', 'Chicken breast fillet', 'Kylling', 'Kjøtt', true, 0, 0, 119, 0, 0, NULL, NULL, NULL, 5, 'Coop'),
  ('Pizzasaus', 'Pizza sauce', 'Saus/tomat', 'Krydder og saus', true, 0, 0, 29, 0, 0, NULL, NULL, NULL, 5, 'Änglamark'),
  ('Hamburgerbrød', 'Burger buns', 'Brød/burger', 'Brød og korn', true, 0, 0, 23, 0, 0, NULL, NULL, NULL, 5, 'Coop; Coop grov'),
  ('Potetgull', 'Potato chips', 'Snacks', 'Snacks', true, 0, 0, 25, 0, 0, NULL, NULL, NULL, 5, 'Kims Paprika Kick; Kims Salt Crunch'),
  ('Baby back ribs', 'Baby back ribs', 'Kjøtt/grill', 'Kjøtt', true, 0, 0, 135, 0, 0, NULL, NULL, NULL, 5, 'Coop'),
  ('Basilikum', 'Basil', 'Krydder/urter', 'Krydder og saus', true, 0, 0, 19, 0, 0, NULL, NULL, NULL, 5, 'Frisk urt'),
  ('Cherrytomater', 'Cherry tomatoes', 'Frukt og grønt', 'Frukt og grønt', true, 0, 0, 17, 0, 0, NULL, NULL, NULL, 5, 'X-tra'),
  ('Cola Zero / Coca-Cola uten sukker', 'Coca-Cola Zero Sugar', 'Drikke', 'Drikke', true, 0, 0, 90, 0, 0, NULL, NULL, NULL, 5, 'Coca-Cola'),
  ('Crispisalat', 'Crisp lettuce', 'Salat', 'Frukt og grønt', true, 0, 0, 35, 0, 0, NULL, NULL, NULL, 5, NULL),
  ('Crème fraîche', 'Crème fraîche', 'Meieri', 'Meieri', true, 0, 0, 30, 0, 0, NULL, NULL, NULL, 5, 'Tine'),
  ('Dusjsåpe', 'Shower gel', 'Personlig hygiene', 'Hus og hjem', true, 0, 0, 33, 0, 0, NULL, NULL, NULL, 5, 'Lano'),
  ('Enchilada kit', 'Enchilada kit', 'Tex-Mex', 'Tørrvarer', true, 0, 0, 73, 0, 0, NULL, NULL, NULL, 5, 'Old El Paso'),
  ('Ferdigmiddag tandoori', 'Ready meal, tandoori', 'Ferdigmiddag', 'Frysevarer', true, 0, 0, 82, 0, 0, NULL, NULL, NULL, 5, 'Fjordland Masala Magic'),
  ('Fiskebuljong', 'Fish stock cubes', 'Buljong', 'Tørrvarer', true, 0, 0, 17, 0, 0, NULL, NULL, NULL, 5, 'Maggi'),
  ('Fullkornswraps', 'Whole wheat wraps', 'Taco/Tex-Mex', 'Tørrvarer', true, 0, 0, 15, 0, 0, NULL, NULL, NULL, 5, 'Coop'),
  ('Grana Padano', 'Grana Padano', 'Ost', 'Ost og pålegg', true, 0, 0, 39, 0, 0, NULL, NULL, NULL, 5, 'Coop'),
  ('Gresk yoghurt', 'Greek yoghurt', 'Meieri', 'Meieri', true, 0, 0, 46, 0, 0, NULL, NULL, NULL, 5, 'Tine'),
  ('Grillribbe', 'Seasoned pork ribs', 'Kjøtt/grill', 'Kjøtt', true, 0, 0, 80, 0, 0, NULL, NULL, NULL, 5, 'Coop krydret'),
  ('Grønnsaksbuljong', 'Vegetable stock cubes', 'Buljong', 'Tørrvarer', true, 0, 0, 17, 0, 0, NULL, NULL, NULL, 5, 'Maggi'),
  ('Havredrikk sjokolade', 'Chocolate oat drink', 'Melkefritt', 'Meieri', true, 0, 0, 35, 0, 0, NULL, NULL, NULL, 5, 'Oatly'),
  ('Iskrem', 'Gelato ice cream', 'Is/dessert', 'Frysevarer', true, 0, 0, 79, 0, 0, NULL, NULL, NULL, 5, 'Gelato Classic'),
  ('Kalkunkorv', 'Turkey sausage', 'Pølser', 'Kjøtt', true, 0, 0, 51, 0, 0, NULL, NULL, NULL, 5, 'Prior'),
  ('Kjøttbuljong', 'Beef stock cubes', 'Buljong', 'Tørrvarer', true, 0, 0, 29, 0, 0, NULL, NULL, NULL, 5, 'Maggi'),
  ('Kokosmelk', 'Coconut milk', 'Hermetikk/curry', 'Tørrvarer', true, 0, 0, 21, 0, 0, NULL, NULL, NULL, 5, 'Coop'),
  ('Krone-is jordbær', 'Strawberry ice cream cone', 'Is/dessert', 'Frysevarer', true, 0, 0, 25, 0, 0, NULL, NULL, NULL, 5, 'Coop'),
  ('Krone-is sjokolade', 'Chocolate ice cream cone', 'Is/dessert', 'Frysevarer', true, 0, 0, 25, 0, 0, NULL, NULL, NULL, 5, 'Coop'),
  ('Lime Kg', 'Lime Kg', 'Ukjent', 'Annet', true, 0, 0, 77, 0, 0, NULL, NULL, NULL, 5, NULL),
  ('Mikropopcorn', 'Microwave popcorn', 'Snacks', 'Snacks', true, 0, 0, 21, 0, 0, NULL, NULL, NULL, 5, 'Coop smør'),
  ('Muskat', 'Nutmeg', 'Krydder', 'Krydder og saus', true, 0, 0, 35, 0, 0, NULL, NULL, NULL, 5, 'Santa Maria malt'),
  ('Pastaskruer fullkorn', 'Whole wheat fusilli', 'Pasta', 'Tørrvarer', true, 0, 0, 28, 0, 0, NULL, NULL, NULL, 5, 'Coop'),
  ('Peanøttsmør', 'Peanut butter', 'Pålegg', 'Ost og pålegg', true, 0, 0, 40, 0, 0, NULL, NULL, NULL, 5, 'Mills'),
  ('Pepperoni', 'Pepperoni', 'Pizza', 'Frysevarer', true, 0, 0, 35, 0, 0, NULL, NULL, NULL, 5, 'Coop'),
  ('Pinsa', 'Pinsa pizza base', 'Pizza', 'Frysevarer', true, 0, 0, 30, 0, 0, NULL, NULL, NULL, 5, 'Coop'),
  ('Pizzabunn fullkorn', 'Whole wheat pizza base', 'Pizza', 'Frysevarer', true, 0, 0, 20, 0, 0, NULL, NULL, NULL, 5, 'Coop'),
  ('Red curry paste', 'Red curry paste', 'Asiatisk/krydder', 'Tørrvarer', true, 0, 0, 30, 0, 0, NULL, NULL, NULL, 5, 'Santa Maria'),
  ('Repsils', 'Throat lozenges', 'Helse/apotek', 'Hus og hjem', true, 0, 0, 60, 0, 0, NULL, NULL, NULL, 5, 'Honning/sitron'),
  ('Rødbetsalat', 'Beetroot salad', 'Tilbehør/pålegg', 'Tørrvarer', true, 0, 0, 33, 0, 0, NULL, NULL, NULL, 5, 'Mills'),
  ('Sjampinjong', 'Mushrooms', 'Frukt og grønt', 'Frukt og grønt', true, 0, 0, 10, 0, 0, NULL, NULL, NULL, 5, 'X-tra 250 g'),
  ('Snackgulrøtter', 'Snack carrots', 'Frukt og grønt', 'Frukt og grønt', true, 0, 0, 10, 0, 0, NULL, NULL, NULL, 5, '250 g'),
  ('Sorbet-is', 'Mango sorbet sticks', 'Is/dessert', 'Frysevarer', true, 0, 0, 30, 0, 0, NULL, NULL, NULL, 5, 'Mango'),
  ('Spaghetti à la Capri', 'Spaghetti à la Capri', 'Ferdigmiddag/pasta', 'Frysevarer', true, 0, 0, 60, 0, 0, NULL, NULL, NULL, 5, 'Toro'),
  ('Spareribs', 'Spareribs', 'Kjøtt/grill', 'Kjøtt', true, 0, 0, 150, 0, 0, NULL, NULL, NULL, 5, 'Coop'),
  ('Sprøbakte crispies', 'Crispy breaded pieces', 'Frysevare/ukjent', 'Frysevarer', true, 0, 0, 42, 0, 0, NULL, NULL, NULL, 5, NULL),
  ('Sum Mix', 'Sum Mix', 'Ukjent', 'Annet', true, 0, 0, 120, 0, 0, NULL, NULL, NULL, 5, NULL),
  ('Svinekoteletter', 'Pork chops', 'Kjøtt', 'Kjøtt', true, 0, 0, 119, 0, 0, NULL, NULL, NULL, 5, 'Marinerte'),
  ('Sweet chili/søt saus', 'Sweet sauce', 'Saus/tilbehør', 'Krydder og saus', true, 0, 0, 55, 0, 0, NULL, NULL, NULL, 5, 'Extra'),
  ('Tacosaus hot', 'Hot taco sauce', 'Taco/Tex-Mex', 'Tørrvarer', true, 0, 0, 22, 0, 0, NULL, NULL, NULL, 5, 'Santa Maria'),
  ('Tortillachips', 'Tortilla chips', 'Taco/Tex-Mex', 'Tørrvarer', true, 0, 0, 42, 0, 0, NULL, NULL, NULL, 5, 'Coop salt'),
  ('Tortillalefser', 'Tortilla wraps', 'Taco/Tex-Mex', 'Tørrvarer', true, 0, 0, 25, 0, 0, NULL, NULL, NULL, 5, 'Old El Paso'),
  ('Yoghurt naturell', 'Plain yoghurt', 'Meieri', 'Meieri', true, 0, 0, 48, 0, 0, NULL, NULL, NULL, 5, 'Tine'),
  ('Yoghurtbeger skogsbær', 'Forest berry yoghurt cups', 'Meieri/barn', 'Meieri', true, 0, 0, 25, 0, 0, NULL, NULL, NULL, 5, NULL),
  ('Yoghurtbeger vanilje', 'Vanilla yoghurt cups', 'Meieri/barn', 'Meieri', true, 0, 0, 39, 0, 0, NULL, NULL, NULL, 5, NULL),
  ('Pizzafyll', 'Pizza filling mix, Toro', 'Pizza/pose', 'Frysevarer', true, 0, 0, 30, 0, 0, NULL, NULL, NULL, 5, 'Toro Mexican; Toro tomat og løk'),
  ('Ricola', 'Throat lozenges', 'Helse/apotek', 'Hus og hjem', true, 0, 0, 30, 0, 0, NULL, NULL, NULL, 5, NULL),
  ('2 Stk A', '2 Stk A', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 56, 56, 56, NULL, 'Rema 1000', 'REMA 1000: 1', 4, NULL),
  ('3 Stk A', '3 Stk A', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 102, 102, 102, NULL, 'Rema 1000', 'REMA 1000: 1', 4, NULL),
  ('4 Stk A', '4 Stk A', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 136, 136, 136, NULL, 'Rema 1000', 'REMA 1000: 1', 4, NULL),
  ('5 Stk A', '5 Stk A', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 125, 125, 125, NULL, 'Rema 1000', 'REMA 1000: 1', 4, NULL),
  ('A Grans Taffel Naturell', 'A Grans Taffel Naturell', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 12, 12, 12, NULL, 'Rema 1000', 'REMA 1000: 1', 4, NULL),
  ('Alpro High Protein Rode Ber 200G', 'Alpro High Protein Rode Ber 200G', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 20, 20, 20, NULL, 'Meny', 'MENY: 1', 4, NULL),
  ('Annet -', 'Annet -', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 51, 51, 51, NULL, 'Rema 1000', 'REMA 1000: 1', 4, NULL),
  ('Batteri Cr2032', 'Batteri Cr2032', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 30, 30, 30, NULL, 'Coop Extra', 'Coop Extra: 1', 4, NULL),
  ('Bjornebzr 125G Beger', 'Bjornebzr 125G Beger', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 43, 43, 43, NULL, 'Meny', 'MENY: 1', 4, NULL),
  ('Bringebær', 'Raspberries', 'Frukt og grønt', 'Frukt og grønt', true, 1, 1, 45, 45, 45, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Brunost', 'Brown cheese', 'Meieri', 'Meieri', true, 1, 1, 56, 56, 56, NULL, 'Coop Extra', 'Coop Extra Hovden: 1', 4, NULL),
  ('Chili& Cheddar Hot', 'Chili& Cheddar Hot', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 31, 31, 31, NULL, 'Rema 1000', 'REMA 1000: 1', 4, NULL),
  ('Chilinetter 175G Eldorado', 'Chilinetter 175G Eldorado', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 28, 28, 28, NULL, 'Meny', 'MENY: 1', 4, NULL),
  ('Coop Fullk.Wr.L 6Stk', 'Coop Fullk.Wr.L 6Stk', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 45, 45, 45, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Coop Grillfilet', 'Coop Grillfilet', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 202, 202, 202, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Coop Grillfilet Bbq', 'Coop Grillfilet Bbq', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 202, 202, 202, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Coop Kokt Skink.100G', 'Coop Kokt Skink.100G', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 23, 23, 23, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Coop Kokt Skink.250G', 'Coop Kokt Skink.250G', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 91, 91, 91, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Coop Pepperoni 100G', 'Coop Pepperoni 100G', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 35, 35, 35, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Coop Pinsa 230G', 'Coop Pinsa 230G', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 150, 150, 150, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Coop Pizzab Fullkorn', 'Coop Pizzab Fullkorn', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 40, 40, 40, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Coop Rosiner 250G', 'Coop Rosiner 250G', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 24, 24, 24, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Def.Dry.Orig.200Ml', 'Def.Dry.Orig.200Ml', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 41, 41, 41, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Def.Men Mould.Clay', 'Def.Men Mould.Clay', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 49, 49, 49, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Dip Tex Mex Style St.Maria', 'Dip Tex Mex Style St.Maria', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 44, 44, 44, NULL, 'Meny', 'MENY: 1', 4, NULL),
  ('Dipmix Holiday 22G Maarud', 'Dipmix Holiday 22G Maarud', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 20, 20, 20, NULL, 'Meny', 'MENY: 1', 4, NULL),
  ('Extra Sweetm.Bottle', 'Extra Sweetm.Bottle', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 55, 55, 55, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Fiskeburger', 'Fish burger', 'Fisk', 'Fisk', true, 1, 1, 165, 165, 165, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Fotball-Lefsa 160G', 'Fotball-Lefsa 160G', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 23, 23, 23, NULL, 'Rema 1000', 'REMA 1000: 1', 4, NULL),
  ('Ge Connattron 100G', 'Ge Connattron 100G', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 27, 27, 27, NULL, 'Rema 1000', 'REMA 1000: 1', 4, NULL),
  ('Gilde Ekte K.Sk.110G', 'Gilde Ekte K.Sk.110G', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 60, 60, 60, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Gilde Fam.Skink.Nat.', 'Gilde Fam.Skink.Nat.', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 33, 33, 33, NULL, 'Coop Extra', 'Coop Extra: 1', 4, NULL),
  ('Grilstad Pepperoni', 'Grilstad Pepperoni', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 36, 36, 36, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Hveteboller 4Pk', 'Hveteboller 4Pk', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 29, 29, 29, NULL, 'Meny', 'MENY: 1', 4, NULL),
  ('Juice', 'Juice', 'Drikke', 'Drikke', true, 1, 1, 20, 20, 20, NULL, 'Meny', 'MENY: 1', 4, NULL),
  ('Kaffebonner', 'Kaffebonner', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 100, 100, 100, NULL, 'Rema 1000', 'REMA 1000: 1', 4, NULL),
  ('Kaviar', 'Cod roe spread', 'Pålegg', 'Ost og pålegg', true, 1, 1, 44, 44, 44, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Kålrot', 'Swede/rutabaga', 'Frukt og grønt', 'Frukt og grønt', true, 1, 1, 31, 31, 31, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Mango Sorbet Sticks', 'Mango Sorbet Sticks', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 30, 30, 30, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Mills Peanut Butter', 'Mills Peanut Butter', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 40, 40, 40, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Mutti Tom.Knust 400G', 'Mutti Tom.Knust 400G', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 41, 41, 41, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Nglamark Solsikkek.', 'Nglamark Solsikkek.', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 24, 24, 24, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Oep Cr.Tor.Ch.Cheese', 'Oep Cr.Tor.Ch.Cheese', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 40, 40, 40, NULL, 'Coop Extra', 'Coop Extra: 1', 4, NULL),
  ('Palm.Dusjs.Men Blue', 'Palm.Dusjs.Men Blue', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 40, 40, 40, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Panert fisk', 'Breaded fish', 'Fisk', 'Fisk', true, 1, 1, 50, 50, 50, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Parmesan/Grana Padano', 'Parmesan/Grana Padano', 'Meieri', 'Meieri', true, 1, 1, 39, 39, 39, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Pepp.Pizzabunn 550G', 'Pepp.Pizzabunn 550G', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 64, 64, 64, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Primo Pane M/Olivenolje 140G Pan Dei Mas', 'Primo Pane M/Olivenolje 140G Pan Dei Mas', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 45, 45, 45, NULL, 'Meny', 'MENY: 1', 4, NULL),
  ('Q F.Yog.Vanilje 800G', 'Q F.Yog.Vanilje 800G', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 38, 38, 38, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Qd Pizzabunn 2Pk', 'Qd Pizzabunn 2Pk', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 70, 70, 70, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Re] Mango', 'Re] Mango', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 1, 1, 1, NULL, 'Rema 1000', 'REMA 1000: 1', 4, NULL),
  ('Ricol.Br.Baer Sitr.M.', 'Ricol.Br.Baer Sitr.M.', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 30, 30, 30, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Rod Chili 50G', 'Rod Chili 50G', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 16, 16, 16, NULL, 'Coop Extra', 'Coop Extra: 1', 4, NULL),
  ('Rod Drue 500G', 'Rod Drue 500G', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 30, 30, 30, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('S.A.G. Gm.Dags.Surk.', 'S.A.G. Gm.Dags.Surk.', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 20, 20, 20, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('S.M.Red Currypaste', 'S.M.Red Currypaste', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 30, 30, 30, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('S.M.Tort.Ch.Sal.185G', 'S.M.Tort.Ch.Sal.185G', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 32, 32, 32, NULL, 'Coop Extra', 'Coop Extra: 1', 4, NULL),
  ('Sitron', 'Lemon', 'Frukt og grønt', 'Frukt og grønt', true, 1, 1, 7, 7, 7, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Smeremyk Lett 400G Eldorado', 'Smeremyk Lett 400G Eldorado', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 80, 80, 80, NULL, 'Meny', 'MENY: 1', 4, NULL),
  ('Søtpotet/søtpotetfries', 'Sweet potato/fries', 'Frukt og grønt', 'Frukt og grønt', true, 1, 1, 64, 64, 64, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Taga Salame Troffel', 'Taga Salame Troffel', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 48, 48, 48, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Tilgodelapp:', 'Tilgodelapp:', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 40, 40, 40, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Toro Pizzafyll Mexic', 'Toro Pizzafyll Mexic', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 52, 52, 52, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Toro Pizzafyll To&Lo', 'Toro Pizzafyll To&Lo', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 60, 60, 60, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Trippel-Trumf + 2%', 'Trippel-Trumf + 2%', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 12, 12, 12, NULL, 'Meny', 'MENY: 1', 4, NULL),
  ('Vannmelon', 'Watermelon', 'Frukt og grønt', 'Frukt og grønt', true, 1, 1, 18, 18, 18, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Xtra Choclate Chip', 'Xtra Choclate Chip', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 35, 35, 35, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Hovden: 1', 4, NULL),
  ('Xtra Serv.Bordp.30Cm', 'Xtra Serv.Bordp.30Cm', 'Ukjent/ikke klassifisert', 'Annet', true, 1, 1, 21, 21, 21, NULL, 'Coop Extra', 'Coop Extra Hovden: 1', 4, NULL),
  ('Barneplaster Sonic 20Stk Salvequick', 'Barneplaster Sonic 20Stk Salvequick', 'Non-food/household', 'Hus og hjem', false, 1, 1, 33, 33, 33, NULL, 'Meny', 'MENY: 1', 4, NULL),
  ('Bzerepose Papir Meny 26] 32X17X40 Cm', 'Bzerepose Papir Meny 26] 32X17X40 Cm', 'Non-food/household', 'Hus og hjem', false, 1, 1, 9, 9, 9, NULL, 'Meny', 'MENY: 1', 4, NULL),
  ('Bzerepose Pr Stk', 'Bzerepose Pr Stk', 'Non-food/household', 'Hus og hjem', false, 1, 1, 7, 7, 7, NULL, 'Meny', 'MENY: 1', 4, NULL),
  ('Bzrepose Pr Stk', 'Bzrepose Pr Stk', 'Non-food/household', 'Hus og hjem', false, 1, 1, 7, 7, 7, NULL, 'Meny', 'MENY: 1', 4, NULL),
  ('Def.Men Sham.Cl.&Fr.', 'Def.Men Sham.Cl.&Fr.', 'Non-food/household', 'Hus og hjem', false, 1, 1, 21, 21, 21, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Def.Sham.Cl.&H.400Ml', 'Def.Sham.Cl.&H.400Ml', 'Non-food/household', 'Hus og hjem', false, 1, 1, 51, 51, 51, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Grillsett 2 Deler', 'Grillsett 2 Deler', 'Non-food/household', 'Hus og hjem', false, 1, 1, 99, 99, 99, NULL, 'Coop Extra', 'Coop Extra Hovden: 1', 4, NULL),
  ('Handlenett Extra', 'Handlenett Extra', 'Non-food/household', 'Hus og hjem', false, 1, 1, 20, 20, 20, NULL, 'Coop Extra', 'Coop Extra Hovden: 1', 4, NULL),
  ('Ibux Tabl.200Mg', 'Ibux Tabl.200Mg', 'Non-food/household', 'Hus og hjem', false, 1, 1, 62, 62, 62, NULL, 'Coop Extra', 'Coop Extra Hovden: 1', 4, NULL),
  ('Kleenex Lommetorkle Allergy Comf.8X9Stk', 'Kleenex Lommetorkle Allergy Comf.8X9Stk', 'Non-food/household', 'Hus og hjem', false, 1, 1, 40, 40, 40, NULL, 'Meny', 'MENY: 1', 4, NULL),
  ('Lano Dusjsape 250Ml', 'Lano Dusjsape 250Ml', 'Non-food/household', 'Hus og hjem', false, 1, 1, 33, 33, 33, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Linea Bokmerker', 'Linea Bokmerker', 'Non-food/household', 'Hus og hjem', false, 1, 1, 50, 50, 50, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Hovden: 1', 4, NULL),
  ('Opptenningsposer 100Stk Burner', 'Opptenningsposer 100Stk Burner', 'Non-food/household', 'Hus og hjem', false, 1, 1, 89, 89, 89, NULL, 'Meny', 'MENY: 1', 4, NULL),
  ('Palmolive Deo', 'Palmolive Deo', 'Non-food/household', 'Hus og hjem', false, 1, 1, 25, 25, 25, NULL, 'Rema 1000', 'REMA 1000: 1', 4, NULL),
  ('Plaster Aqua Block 16Stk Salvequick', 'Plaster Aqua Block 16Stk Salvequick', 'Non-food/household', 'Hus og hjem', false, 1, 1, 60, 60, 60, NULL, 'Meny', 'MENY: 1', 4, NULL),
  ('Repsils Hon.&Sit.56G', 'Repsils Hon.&Sit.56G', 'Non-food/household', 'Hus og hjem', false, 1, 1, 60, 60, 60, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Ricola Original', 'Ricola Original', 'Non-food/household', 'Hus og hjem', false, 1, 1, 30, 30, 30, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Sjamp. X-Tra 250G', 'Sjamp. X-Tra 250G', 'Non-food/household', 'Hus og hjem', false, 1, 1, 10, 10, 10, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Telys Gullk.8T 50Stk', 'Telys Gullk.8T 50Stk', 'Non-food/household', 'Hus og hjem', false, 1, 1, 98, 98, 98, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Tritan Drikkeflaske', 'Tritan Drikkeflaske', 'Non-food/household', 'Hus og hjem', false, 1, 1, 358, 358, 358, 'Sjelden/enkeltkjøp', 'Coop Extra', 'Coop Extra Hovden: 1', 4, NULL),
  ('Turshorts Ekkertind', 'Turshorts Ekkertind', 'Non-food/household', 'Hus og hjem', false, 1, 1, 349, 349, 349, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Zalo Ultra 5Dl', 'Zalo Ultra 5Dl', 'Non-food/household', 'Hus og hjem', false, 1, 1, 34, 34, 34, NULL, 'Coop Extra', 'Coop Extra Dr. Munk: 1', 4, NULL),
  ('Aprikossyltetøy', 'Apricot jam, Nora homemade style', 'Syltetøy', 'Ost og pålegg', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Noras hjemmelagede'),
  ('Baconost', 'Bacon cheese spread', 'Pålegg', 'Ost og pålegg', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Bakepulver', 'Baking powder', 'Baking', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Bali-gryte', 'Bali chicken casserole mix', 'Gryterett/pose', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Toro'),
  ('Big One pizza', 'Big One frozen pizza', 'Ferdigmat/pizza', 'Frysevarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Big One'),
  ('Blåbærsyltetøy', 'Blueberry jam', 'Syltetøy', 'Ost og pålegg', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Bretagne-saus', 'Brittany-style sauce', 'Saus/pose', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Toro'),
  ('Brokkoliblanding', 'Broccoli vegetable mix', 'Frysegrønt', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Brun saus', 'Brown gravy', 'Saus', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Brunt sukker', 'Brown sugar', 'Baking', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Brus', 'Soda / soft drink', 'Drikke', 'Drikke', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Bær til matpakke', 'Berries for lunchbox', 'Bær', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Béarnaisesaus', 'Béarnaise sauce', 'Saus', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Cheddar', 'Cheddar', 'Ost', 'Ost og pålegg', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Chiafrø', 'Chia seeds', 'Frø/kjerner', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Chili', 'Chili', 'Grønnsaker/krydder', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Chilinøtter', 'Chili nuts', 'Snacks/nøtter', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Cola Zero', 'Coke Zero', 'Drikke', 'Drikke', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Cookies med sjokolade', 'Chocolate chip cookies', 'Kjeks', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Crisp salat', 'Crisp lettuce', 'Salat', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Digestivekjeks', 'Digestive biscuits', 'Kjeks', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Dipp', 'Dip', 'Saus/snacks', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Druer', 'Grapes', 'Frukt', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Røde'),
  ('Eddik', 'Vinegar', 'Olje/eddik', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Enchilada-kit', 'Enchilada kit', 'Taco/Tex-Mex', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Eplecidereddik', 'Apple cider vinegar', 'Olje/eddik', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Eplejuice', 'Apple juice', 'Drikke', 'Drikke', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Estragon', 'Tarragon', 'Krydder/urter', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Fajitas-kit', 'Fajita kit', 'Taco/Tex-Mex', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Feta', 'Feta cheese', 'Ost', 'Ost og pålegg', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Filterkaffe', 'Filter coffee', 'Kaffe', 'Drikke', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Fiskekaker', 'Fish cakes, Rema 1000', 'Fisk', 'Fisk', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Rema 1000'),
  ('Flatbrød', 'Norwegian flatbread', 'Brød/korn', 'Brød og korn', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Flytende honning', 'Liquid honey', 'Søtning', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Fløtegratinerte poteter', 'Creamy potato gratin', 'Tilbehør', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Fløtesaus', 'Cream sauce', 'Saus', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Frokostblanding', 'Breakfast cereal', 'Frokost/korn', 'Brød og korn', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Frosne blåbær', 'Frozen blueberries', 'Bær/frys', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Frosne jordbær', 'Frozen strawberries', 'Bær/frys', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Frosne vårruller', 'Frozen spring rolls', 'Ferdigmat/frys', 'Frysevarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Frossen grønnsaksmiks', 'Frozen vegetable mix', 'Frysegrønt', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Fullkornsmakaroni', 'Whole wheat macaroni', 'Pasta', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Gaffelbiter', 'Pickled herring pieces', 'Fisk/pålegg', 'Fisk', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Gelé', 'Jelly / gelatin dessert', 'Dessert/baking', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Sitron og jordbær'),
  ('Glutenfrie fiskekaker', 'Gluten-free fish cakes', 'Fisk', 'Fisk', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Rema 1000'),
  ('Grapefrukt', 'Grapefruit', 'Frukt', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Gresskar', 'Pumpkin', 'Grønnsaker/sesong', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Gresskarkjerner', 'Pumpkin seeds', 'Frø/kjerner', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Grillet kylling', 'Grilled chicken', 'Kylling', 'Kjøtt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Grillkjøtt', 'Barbecue meat', 'Kjøtt/grill', 'Kjøtt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Grillkrydder', 'Barbecue seasoning', 'Krydder', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Grillpølser', 'Grill sausages', 'Pølser', 'Kjøtt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Coop'),
  ('Grovt mel', 'Wholemeal flour', 'Mel/baking', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Grøt', 'Porridge', 'Frokost/middag', 'Brød og korn', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Coop Extra / Fjordland'),
  ('Hamburgerdressing', 'Burger dressing', 'Saus', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Havrefras', 'Oat cereal', 'Frokost/korn', 'Brød og korn', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Havregryn', 'Rolled oats', 'Frokost/korn', 'Brød og korn', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Lettkokte'),
  ('Havremel', 'Oat flour', 'Mel/baking', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Hel pepper', 'Whole pepper', 'Krydder', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Hermetiske tomater', 'Canned tomatoes', 'Hermetikk', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Hodekål', 'Cabbage', 'Grønnsaker', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Hvite bønner', 'White beans', 'Belgvekster', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Hvitløk', 'Garlic', 'Grønnsaker', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Hvitløksbaguetter', 'Garlic baguettes', 'Brød/tilbehør', 'Brød og korn', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Hvitløksdressing', 'Garlic dressing', 'Saus', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Hvitost', 'White/yellow cheese', 'Ost', 'Ost og pålegg', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Is til BJ', 'Ice cream for BJ', 'Is/dessert', 'Frysevarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Julepølse', 'Christmas sausage', 'Pølser', 'Kjøtt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Juleskinke', 'Christmas ham', 'Kjøtt/jul', 'Kjøtt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Julesylte', 'Christmas head cheese', 'Pålegg/jul', 'Ost og pålegg', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Kaffebønner', 'Coffee beans', 'Kaffe', 'Drikke', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Kakao', 'Instant cocoa', 'Drikke/dessert', 'Drikke', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Rett i koppen'),
  ('Kalkunpølse', 'Turkey sausage', 'Pølser', 'Kjøtt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Kanel', 'Cinnamon', 'Krydder/baking', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Karbonadedeig', 'Lean minced beef', 'Kjøtt', 'Kjøtt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Kardemomme', 'Cardamom', 'Krydder/baking', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Kjeks', 'Cookies, Oreo', 'Kjeks', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Oreo'),
  ('Kjøttkaker', 'Norwegian meat cakes', 'Kjøtt/middag', 'Kjøtt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Kjøttpølse', 'Meat sausage', 'Pølser', 'Kjøtt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Klementiner', 'Clementines', 'Frukt', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Kokesjokolade', 'Cooking chocolate', 'Sjokolade/baking', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, '46%'),
  ('Kornmo knekkebrød', 'Kornmo crispbread', 'Knekkebrød', 'Brød og korn', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Kornmo'),
  ('Koteletter', 'Pork chops', 'Kjøtt', 'Kjøtt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Kremfløte', 'Whipping cream', 'Meieri', 'Meieri', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Kroneis', 'Norwegian cone ice cream', 'Is/dessert', 'Frysevarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Med og uten melk'),
  ('Kullsyrevann', 'Sparkling water', 'Drikke', 'Drikke', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Kulturmelk', 'Cultured milk / buttermilk', 'Meieri', 'Meieri', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Kumelk', 'Cow''s milk', 'Meieri', 'Meieri', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Kvikklunsj', 'Kvikk Lunsj chocolate bar', 'Godteri', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Kyllinglår', 'Raw frozen chicken thighs', 'Kylling', 'Kjøtt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Frosne rå'),
  ('Kyllingsaus', 'Chicken sauce', 'Saus', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Lammelår', 'Leg of lamb', 'Kjøtt/sesong', 'Kjøtt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Lapskausblanding', 'Frozen stew vegetable mix', 'Frysegrønt', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Lapskausbokser', 'Canned Norwegian stew', 'Ferdigmat', 'Frysevarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Lys'),
  ('Lapskausposer', 'Frozen stew packs', 'Ferdigmat/frys', 'Frysevarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Linfrø', 'Flax seeds', 'Frø/kjerner', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Lomper', 'Potato flatbreads', 'Brød/pølser', 'Brød og korn', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Lørdagsgodt', 'Saturday sweets', 'Godteri', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Maiskolber', 'Corn on the cob', 'Grønnsaker/grill', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Majones', 'Mayonnaise', 'Saus/pålegg', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Mango', 'Mango', 'Frukt', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Mango chutney', 'Mango chutney', 'Saus/tilbehør', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Marshmallows', 'Marshmallows', 'Godteri', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Matfløte', 'Cooking cream', 'Meieri', 'Meieri', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Matolje', 'Cooking oil', 'Olje/eddik', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Medisterkaker', 'Christmas pork patties', 'Kjøtt/jul', 'Kjøtt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Melis', 'Icing sugar', 'Baking', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Melkefri yoghurt naturell', 'Dairy-free plain yoghurt', 'Melkefritt', 'Meieri', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Melkesjokolade', 'Milk chocolate', 'Sjokolade', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Mozzarella ostestenger', 'Mozzarella cheese sticks, Synnøve', 'Ost', 'Ost og pålegg', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Synnøve'),
  ('Mørk sjokolade 70%', '70% dark chocolate', 'Sjokolade', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Med havsalt'),
  ('Müsli', 'Muesli', 'Frokost/korn', 'Brød og korn', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Nachochips', 'Nacho chips', 'Taco/Tex-Mex', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Nonstop', 'Nonstop candy', 'Godteri', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Nudler', 'Noodles', 'Tørrvarer', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Nøtter', 'Nuts', 'Nøtter', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Olivenolje', 'Olive oil', 'Olje/eddik', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Paprikachips', 'Paprika chips', 'Snacks', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Parmesanost', 'Parmesan cheese', 'Ost', 'Ost og pålegg', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Passata', 'Tomato passata, Mutti', 'Hermetikk/tomat', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Mutti'),
  ('Pasta', 'Pasta', 'Tørrvarer', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Pastaskruer', 'Pasta twists / fusilli', 'Pasta', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Pastinakk', 'Parsnip', 'Grønnsaker', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Pepsi Max', 'Pepsi Max', 'Drikke', 'Drikke', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Pinjekjerner', 'Pine nuts', 'Frø/kjerner', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Pizza', 'Pizza', 'Ferdigmat/pizza', 'Frysevarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Pizzamel', 'Pizza flour', 'Mel/baking', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Polarbrød', 'Polar bread', 'Brød og korn', 'Brød og korn', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Potetmel', 'Potato starch', 'Mel/baking', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Pølsebrød', 'Hot dog buns', 'Brød/pølser', 'Brød og korn', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Rekesalat', 'Shrimp salad', 'Pålegg/sjømat', 'Ost og pålegg', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Risgrøt', 'Rice porridge', 'Frokost/middag', 'Brød og korn', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Rosiner', 'Raisins', 'Tørket frukt', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Rosmarin', 'Rosemary', 'Krydder/urter', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Frisk'),
  ('Runde knekkebrød', 'Round crispbread', 'Knekkebrød', 'Brød og korn', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Ryvita knekkebrød', 'Ryvita crispbread', 'Knekkebrød', 'Brød og korn', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Ryvita'),
  ('Røde linser', 'Red lentils', 'Belgvekster', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Rødkål', 'Red cabbage', 'Tilbehør/jul', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Rødvinssaus', 'Red wine sauce', 'Saus', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Rømme', 'Sour cream', 'Meieri', 'Meieri', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Rømme uten melk', 'Dairy-free sour cream', 'Melkefritt', 'Meieri', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Rømmedressing', 'Sour cream dressing', 'Saus', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Rema 1000'),
  ('Saft', 'Squash / cordial', 'Drikke', 'Drikke', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Salsa', 'Mild salsa', 'Taco/Tex-Mex', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Mild'),
  ('Salt', 'Salt', 'Krydder', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Saltstenger', 'Pretzel sticks', 'Snacks', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Sammalt hvete grov', 'Coarse whole wheat flour', 'Mel/baking', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Seigmenn', 'Norwegian gummy candy', 'Godteri', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Sellerirot', 'Celeriac', 'Grønnsaker', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Servelat', 'Servelat sausage', 'Pålegg', 'Ost og pålegg', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Sesamfrø', 'Sesame seeds', 'Frø/kjerner', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Siktet hvetemel', 'Plain white wheat flour', 'Mel/baking', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Siktet rugmel', 'Fine rye flour', 'Mel/baking', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Siktet speltmel', 'Sifted spelt flour', 'Mel/baking', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Sjokade', 'Chocolate spread', 'Pålegg', 'Ost og pålegg', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Sjysaus', 'Gravy / jus sauce', 'Saus', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Skinke i små biter', 'Diced ham', 'Pålegg/pizza', 'Ost og pålegg', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Skinnfrie pølser', 'Skinless sausages', 'Pølser', 'Kjøtt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Smoothiefrukt', 'Smoothie fruit mix', 'Bær/frukt frys', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Smågodt', 'Pick-and-mix candy', 'Godteri', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Smør', 'Butter, Eldorado', 'Meieri', 'Meieri', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Eldorado'),
  ('Smøremykt', 'Spreadable butter blend', 'Meieri', 'Meieri', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Solo', 'Solo orange soda', 'Drikke', 'Drikke', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Solsikkekjerner', 'Sunflower seeds', 'Frø/kjerner', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Sommerkoteletter', 'Pork summer chops', 'Kjøtt', 'Kjøtt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Soyasaus', 'Soy sauce, Kikkoman green', 'Saus', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Kikkoman grønn'),
  ('Spagetti', 'Spaghetti', 'Pasta', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Spagetti à la Capri', 'Canned spaghetti à la Capri', 'Ferdigmat', 'Frysevarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Spekeskinke', 'Cured ham / prosciutto', 'Pålegg', 'Ost og pålegg', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Sriracha', 'Sriracha', 'Saus', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Stangselleri', 'Celery stalks', 'Grønnsaker', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Sukker', 'Sugar', 'Baking', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Sukkerkulør', 'Caramel coloring for gravy', 'Saus/krydder', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Sunn chips', 'Healthier chips', 'Snacks', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Til mor'),
  ('Surkål', 'Sauerkraut', 'Tilbehør/jul', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Svarte bønner', 'Black beans', 'Belgvekster', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Sweet chilisaus', 'Sweet chili sauce', 'Saus', 'Krydder og saus', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Syltetøy', 'Jam', 'Syltetøy', 'Ost og pålegg', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Søtpotet', 'Sweet potato', 'Grønnsaker', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Tacolefser', 'Tortillas', 'Taco/Tex-Mex', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Tacosaus', 'Taco sauce', 'Taco/Tex-Mex', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Mild/hot'),
  ('Tacoskjell', 'Taco shells', 'Taco/Tex-Mex', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Tomater', 'Tomatoes, small Norwegian', 'Grønnsaker', 'Frukt og grønt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Små norske'),
  ('Tomatpuré', 'Tomato purée', 'Hermetikk/tomat', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Tube'),
  ('Tomatsuppe', 'Tomato soup', 'Suppe', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Toro/vegansk'),
  ('Turkjeks', 'Hiking biscuits', 'Kjeks', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Tyggisboks', 'Chewing gum tub', 'Godteri', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Tynnribbe', 'Pork belly rib', 'Kjøtt/jul', 'Kjøtt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Tørrgjær', 'Dry yeast', 'Baking', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Blå'),
  ('Valnøtter', 'Walnuts', 'Nøtter', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Vaniljedessert', 'Vanilla dessert cups', 'Dessert', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, '4-pk'),
  ('Vaniljeis', 'Vanilla ice cream', 'Is/dessert', 'Frysevarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Med og uten melk'),
  ('Vaniljekrem', 'Vanilla custard cream', 'Dessert/baking', 'Snacks', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Vaniljesukker', 'Vanilla sugar', 'Baking', 'Tørrvarer', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Vanlig fløte', 'Cream', 'Meieri', 'Meieri', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Vegansk kremost', 'Vegan cream cheese', 'Melkefritt', 'Meieri', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Meny'),
  ('Vegansk majones', 'Vegan mayonnaise', 'Melkefritt/vegansk', 'Meieri', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Vegansk revet ost', 'Vegan grated cheese', 'Melkefritt', 'Meieri', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Gryr'),
  ('Vegansk yoghurt naturell', 'Plain vegan yoghurt', 'Melkefritt', 'Meieri', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Meny'),
  ('Vin', 'Wine', 'Drikke/voksen', 'Drikke', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Wienerpølser', 'Wiener sausages', 'Pølser', 'Kjøtt', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, NULL),
  ('Yoghurtbeger', 'Small yoghurt cups', 'Meieri/melkefritt', 'Meieri', true, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 'Til BJ')
on conflict (name) do nothing;

-- Normaliseringsregler: 134 regler
insert into public.norm_rules (from_text, to_text) values
  ('Norwegia', 'Norvegia'),
  ('Ketshup', 'Ketchup'),
  ('ketshup', 'Ketchup'),
  ('Broccoli', 'Brokkoli'),
  ('Avocado', 'Avokado'),
  ('advokado', 'Avokado'),
  ('advoado', 'Avokado'),
  ('Makrellitomat', 'Makrell i tomat'),
  ('makrel', 'Makrell i tomat'),
  ('Mozarella', 'Mozzarella'),
  ('Ruccula', 'Ruccola'),
  ('Permesan', 'Parmesanost'),
  ('Tacoktydder', 'Tacokrydder'),
  ('Gulerøtter', 'Gulrøtter'),
  ('Kålrabi', 'Kålrot'),
  ('Dopapir', 'Toalettpapir'),
  ('Tørkepapir', 'Tørkerull'),
  ('Burgerbrød', 'Hamburgerbrød'),
  ('Burger', 'Hamburgere'),
  ('burgere', 'Hamburgere'),
  ('Lefte', 'Lefse / tacolefser'),
  ('Hvitøk', 'Hvitløk'),
  ('Siratcha', 'Sriracha'),
  ('Lasansje', 'Lasagne'),
  ('ALPRO SOYADRI', 'Soyamelk uten sukker, Alpro'),
  ('KOKOSMELK', 'Kokosmelk, Coop'),
  ('KOKT SKINK', 'Kokt skinke, Coop'),
  ('KYLLINGFI', 'Kyllingfilet, Coop'),
  ('MAIS 3PK', 'Mais, Coop 3-pk'),
  ('MICROPOPC', 'Mikropopcorn, Coop smør'),
  ('POTETSALAT', 'Potetsalat, Coop/Klassisk'),
  ('TORT.CHIPS', 'Tortillachips, Coop salt'),
  ('COTT.CH', 'Cottage cheese, Mager'),
  ('COTT.CHE', 'Cottage cheese, Mager'),
  ('JUBELSALAM', 'Salami, Grilstad Jubelsalami'),
  ('GULROT', 'Gulrøtter, X-tra / snack / bunt'),
  ('KIMS PAPRIKA KICK', 'Potetgull, Kims Paprika Kick'),
  ('KIMS SALT CRUNCH', 'Potetgull, Kims Salt Crunch'),
  ('KIWI GRØNN', 'Kiwi'),
  ('KRONE-IS', 'Krone-is, Coop / Cookie Dough / jordbær / sjokolade'),
  ('GELATO IS', 'Iskrem, Gelato Classic'),
  ('MANGO SORBET', 'Sorbet-is, Mango'),
  ('LAMBI TOA.PAPIR', 'Toalettpapir, Lambi 24-pk'),
  ('LER.PANERT RØDSPETTE', 'Rødspette, Lerøy panert'),
  ('LØK STRØMPE', 'Løk, 700 g strømpe'),
  ('KYLLINGBULJONG', 'Kyllingbuljong, Maggi'),
  ('FISKEBULJONG', 'Fiskebuljong, Maggi'),
  ('GR.SAKSBULJONG', 'Grønnsaksbuljong, Maggi'),
  ('KJØTTBULJONG', 'Kjøttbuljong, Maggi'),
  ('MILLS KAVIAR', 'Kaviar, Mills tube'),
  ('RØDBETSALAT', 'Rødbetsalat, Mills'),
  ('NORA JORDBÆRSY', 'Jordbærsyltetøy, Nora'),
  ('NUGATTI', 'Nugatti, 500 g'),
  ('ENCHILADA KIT', 'Enchilada kit, Old El Paso'),
  ('OEP TORTIL', 'Tortillalefser, Old El Paso'),
  ('FULLK.WR', 'Fullkornswraps, Coop'),
  ('KALKUNKOR', 'Kalkunkorv, Prior'),
  ('RED CURRYPASTE', 'Red curry paste, Santa Maria'),
  ('SITRONER', 'Sitron'),
  ('STABBUR-MAKRELL', 'Makrell i tomat, Stabbur'),
  ('TINE LETTM', 'Lettmelk, Tine 0,5% 1,75 L'),
  ('Q-MELK LE', 'Lettmelk, Q-Meieriene 0,5% 1,75 L'),
  ('LETTRØM', 'Lettrømme, Tine 17% 300 g'),
  ('TINE YOGHURT NAT', 'Yoghurt naturell, Tine'),
  ('TINE GRESK YOGH', 'Gresk yoghurt, Tine'),
  ('TINE ØKONOMIPAKKE', 'Gulost, Tine økonomipakke'),
  ('NORVEGIA DUOPACK', 'Gulost, Norvegia Duopack'),
  ('TUB.LITE', 'Øl, Tuborg Lite'),
  ('WASA RUGSPRØ', 'Rugsprø, Wasa'),
  ('XTRA EGG', 'Egg, Xtra 12-pk'),
  ('COOP EGG FRITTG', 'Egg, Coop frittgående 18-pk'),
  ('COOP KRONE-IS JORDBR', 'Krone-is jordbær, Coop'),
  ('COOP KRONE-IS SJOKOL', 'Krone-is sjokolade, Coop'),
  ('COOP PEPPERONI', 'Pepperoni, Coop'),
  ('PEPPERONI', 'Pepperoni, Coop'),
  ('PIZZAB FULLKORN', 'Pizzabunn fullkorn, Coop'),
  ('PEPP.PIZZABUNN', 'Pizzabunn, Peppes'),
  ('QD PIZZABUNN', 'Pizzabunn, Q/QD 2-pk'),
  ('COOP PINSA', 'Pinsa, Coop'),
  ('HEINZ KETCHUP', 'Ketchup, Heinz'),
  ('PIZZAFYLL MEXIC', 'Pizzafyll, Toro Mexican'),
  ('PIZZAFYLL TO&LØ', 'Pizzafyll, Toro tomat og løk'),
  ('PIZZA SAUS', 'Pizzasaus, Änglamark'),
  ('COOP SUPERBRØD', 'Brød, Coop Superbrød 750 g'),
  ('HAVREGULLBRØD', 'Brød, Coop Havregullbrød'),
  ('FJL MASALAMAGIC', 'Ferdigmiddag tandoori, Fjordland Masala Magic'),
  ('SPAGH.A LA CAPRI', 'Spaghetti à la Capri, Toro'),
  ('ÃM TOMATER FINMOST', 'Finmoste tomater, Änglamark'),
  ('AVOKADO', 'Avokado, Modnet 2-pk'),
  ('FULLK.SPAGHET', 'Fullkornsspagetti, Barilla'),
  ('BARILLA LASAGNE', 'Lasagneplater, Barilla'),
  ('COCA COLA UTS', 'Cola Zero / Coca-Cola uten sukker, Coca-Cola'),
  ('BURGERBRØD', 'Hamburgerbrød, Coop'),
  ('BURGERBR', 'Hamburgerbrød, Coop grov'),
  ('FUSILLI FULLK', 'Pastaskruer fullkorn, Coop'),
  ('HA.TOM.URT', 'Hakkede tomater med urter, Coop'),
  ('HAK.TOM.HVITLØK', 'Hakkede tomater med hvitløk, Coop'),
  ('FISKEBURGER', 'Fiskeburger, Hyse og torsk'),
  ('GILDE BURGER', 'Hamburgere, Gilde 800 g'),
  ('GRYR KOKOS', 'Gryr fløte, Gryr kokos/raps'),
  ('RAPS', 'Gryr fløte, Gryr kokos/raps'),
  ('ISBERG', 'Isbergsalat, Änglamark'),
  ('LANO DUSJSÅPE', 'Dusjsåpe, Lano'),
  ('PAPRIKA', 'Paprika, X-tra'),
  ('PINK LADY', 'Epler, Pink Lady 6-pk'),
  ('POTET X-TRA', 'Poteter, X-tra 4 kg'),
  ('TACO SAUCE HOT', 'Tacosaus hot, Santa Maria'),
  ('TACO SPICEMI', 'Tacokrydder, Santa Maria 3-pk'),
  ('SALAT CRISPI', 'Crispisalat'),
  ('SALATOST', 'Feta/salatost, Urter/hvitløk'),
  ('BRETAGNESAUS', 'Bretagne saus, Toro familiepakke'),
  ('XTRA KJØTTDEIG', 'Kjøttdeig, Xtra'),
  ('XTRA LAKSEFILET', 'Laks, Xtra laksefilet 4-pk'),
  ('YOGH.SKOGSB', 'Yoghurtbeger skogsbær'),
  ('YOGH.VANILJE', 'Yoghurtbeger vanilje'),
  ('SNACK GULROT', 'Snackgulrøtter, 250 g'),
  ('BANAN', 'Bananer, X-tra'),
  ('BÆR BRINGEBÆR', 'Bringebær, 225 g'),
  ('BABY BACK RIBS', 'Baby back ribs, Coop'),
  ('GRANA PADANO', 'Grana Padano, Coop'),
  ('GRILLRIBBE', 'Grillribbe, Coop krydret'),
  ('COOP SPARERIBS', 'Spareribs, Coop'),
  ('EXTRA SWEETM', 'Sweet chili/søt saus, Extra'),
  ('BASILIK', 'Basilikum, Frisk urt'),
  ('PEANUT BUTTER', 'Peanøttsmør, Mills'),
  ('HAVREDR.SJO', 'Havredrikk sjokolade, Oatly'),
  ('REPSILS', 'Repsils, Honning/sitron'),
  ('RICOL', 'Ricola'),
  ('MUSKATNØTT', 'Muskat, Santa Maria malt'),
  ('SJAMP', 'Sjampinjong, X-tra 250 g'),
  ('SVINEKOTELETTER', 'Svinekoteletter, Marinerte'),
  ('SALAME TRØFFEL', 'Salami, Taga trøffelsalami'),
  ('CRÈME FRAÎCHE', 'Crème fraîche, Tine'),
  ('TOMAT CHERRY', 'Cherrytomater, X-tra')
on conflict (from_text) do nothing;

-- Middagsbibliotek: 30 middager (mengder for 2 voksne + 2 barn)
insert into public.meal_library (name, category, ingredients) values
  ('Taco', 'Tex-Mex', '[{"n":"Kjøttdeig","qty":1},{"n":"Tacolefser","qty":2},{"n":"Tacokrydder","qty":1},{"n":"Tacosaus","qty":1},{"n":"Mais","qty":1},{"n":"Agurk","qty":1},{"n":"Paprika","qty":1},{"n":"Tomater","qty":2},{"n":"Revet ost","qty":1},{"n":"Avokado","qty":2},{"n":"Tacoskjell","qty":1}]'::jsonb),
  ('Spagetti med kjøttsaus', 'Pasta', '[{"n":"Kjøttdeig","qty":1},{"n":"Spagetti","qty":1},{"n":"Passata","qty":1},{"n":"Løk","qty":1},{"n":"Gulrøtter","qty":2},{"n":"Revet ost","qty":1}]'::jsonb),
  ('Lasagne', 'Pasta', '[{"n":"Kjøttdeig","qty":1},{"n":"Lasagneplater","qty":1},{"n":"Passata","qty":2},{"n":"Hvit saus","qty":1},{"n":"Revet ost","qty":1},{"n":"Løk","qty":1}]'::jsonb),
  ('Ovnsbakt laks', 'Fisk', '[{"n":"Laksefilet","qty":2},{"n":"Poteter","qty":1},{"n":"Brokkoli","qty":1},{"n":"Gulrøtter","qty":3},{"n":"Sitron","qty":1}]'::jsonb),
  ('Fiskekaker', 'Fisk', '[{"n":"Fiskekaker","qty":8},{"n":"Poteter","qty":1},{"n":"Gulrøtter","qty":3},{"n":"Smør","qty":1}]'::jsonb),
  ('Fiskepinner', 'Fisk', '[{"n":"Fiskepinner","qty":12},{"n":"Poteter","qty":1},{"n":"Erter","qty":1},{"n":"Remulade","qty":1}]'::jsonb),
  ('Panert sei', 'Fisk', '[{"n":"Panert sei","qty":4},{"n":"Poteter","qty":1},{"n":"Gulrøtter","qty":2},{"n":"Agurk","qty":1}]'::jsonb),
  ('Hamburgere', 'Grill', '[{"n":"Hamburgere","qty":6},{"n":"Burgerbrød","qty":6},{"n":"Burgerost","qty":6},{"n":"Salat","qty":1},{"n":"Tomater","qty":2},{"n":"Agurk","qty":1},{"n":"Dressing","qty":1}]'::jsonb),
  ('Pølser med lompe', 'Grill', '[{"n":"Pølser","qty":8},{"n":"Lomper","qty":1},{"n":"Ketchup","qty":1},{"n":"Sprøstekt løk","qty":1}]'::jsonb),
  ('Hjemmelaget pizza', 'Pizza', '[{"n":"Pizzabunn","qty":2},{"n":"Passata","qty":1},{"n":"Revet ost","qty":2},{"n":"Kokt skinke","qty":1},{"n":"Paprika","qty":1},{"n":"Mais","qty":1}]'::jsonb),
  ('Pizza fredag (frossen)', 'Pizza', '[{"n":"Frossenpizza","qty":2},{"n":"Salat","qty":1},{"n":"Agurk","qty":1}]'::jsonb),
  ('Kylling curry', 'Kylling', '[{"n":"Kyllingfilet","qty":3},{"n":"Ris","qty":1},{"n":"Currysaus","qty":1},{"n":"Paprika","qty":1},{"n":"Løk","qty":1},{"n":"Gryr fløte","qty":1}]'::jsonb),
  ('Kylling og ris', 'Kylling', '[{"n":"Kyllingfilet","qty":3},{"n":"Ris","qty":1},{"n":"Brokkoli","qty":1},{"n":"Mais","qty":1},{"n":"Soyasaus","qty":1}]'::jsonb),
  ('Kyllingwok', 'Kylling', '[{"n":"Kyllingfilet","qty":3},{"n":"Wokgrønnsaker","qty":1},{"n":"Nudler","qty":2},{"n":"Woksaus","qty":1}]'::jsonb),
  ('Kjøttkaker i brun saus', 'Tradisjon', '[{"n":"Kjøttkaker","qty":12},{"n":"Poteter","qty":1},{"n":"Brun saus","qty":1},{"n":"Erter","qty":1},{"n":"Tyttebær","qty":1}]'::jsonb),
  ('Kjøttdeigsaus med ris', 'Tradisjon', '[{"n":"Kjøttdeig","qty":1},{"n":"Ris","qty":1},{"n":"Løk","qty":1},{"n":"Passata","qty":1},{"n":"Mais","qty":1}]'::jsonb),
  ('Pannekaker', 'Kos', '[{"n":"Hvetemel","qty":1},{"n":"Egg","qty":6},{"n":"Melk","qty":1},{"n":"Syltetøy","qty":1},{"n":"Bacon","qty":1}]'::jsonb),
  ('Tomatsuppe med makaroni', 'Suppe', '[{"n":"Tomatsuppe","qty":2},{"n":"Makaroni","qty":1},{"n":"Egg","qty":4},{"n":"Brød","qty":1}]'::jsonb),
  ('Grønnsakssuppe', 'Suppe', '[{"n":"Suppegrønnsaker","qty":1},{"n":"Buljong","qty":2},{"n":"Kjøttboller","qty":1},{"n":"Brød","qty":1}]'::jsonb),
  ('Fish and chips', 'Fisk', '[{"n":"Panert torsk","qty":4},{"n":"Pommes frites","qty":1},{"n":"Erter","qty":1},{"n":"Remulade","qty":1}]'::jsonb),
  ('Omelett med skinke', 'Rask', '[{"n":"Egg","qty":8},{"n":"Kokt skinke","qty":1},{"n":"Revet ost","qty":1},{"n":"Paprika","qty":1},{"n":"Brød","qty":1}]'::jsonb),
  ('Grøt (havregrøt/risgrøt)', 'Kos', '[{"n":"Risgrøt","qty":2},{"n":"Sukker","qty":1},{"n":"Kanel","qty":1},{"n":"Smør","qty":1}]'::jsonb),
  ('Tortellini med pesto', 'Pasta', '[{"n":"Tortellini","qty":2},{"n":"Pesto","qty":1},{"n":"Cherrytomater","qty":1},{"n":"Parmesan","qty":1}]'::jsonb),
  ('Wraps med kylling', 'Rask', '[{"n":"Kyllingfilet","qty":2},{"n":"Tortilla","qty":8},{"n":"Salat","qty":1},{"n":"Mais","qty":1},{"n":"Rømme","qty":1},{"n":"Revet ost","qty":1}]'::jsonb),
  ('Pølsegryte', 'Gryte', '[{"n":"Pølser","qty":6},{"n":"Makaroni","qty":1},{"n":"Passata","qty":1},{"n":"Paprika","qty":1},{"n":"Løk","qty":1}]'::jsonb),
  ('Chili con carne (mild)', 'Gryte', '[{"n":"Kjøttdeig","qty":1},{"n":"Bønner i chilisaus","qty":2},{"n":"Ris","qty":1},{"n":"Mais","qty":1},{"n":"Rømme","qty":1}]'::jsonb),
  ('Makrell i tomat på brød', 'Rask', '[{"n":"Makrell i tomat","qty":2},{"n":"Brød","qty":1},{"n":"Egg","qty":4},{"n":"Agurk","qty":1}]'::jsonb),
  ('Pytt i panne', 'Rask', '[{"n":"Poteter","qty":1},{"n":"Pølser","qty":4},{"n":"Løk","qty":1},{"n":"Egg","qty":4},{"n":"Paprika","qty":1}]'::jsonb),
  ('Fiskeburger', 'Fisk', '[{"n":"Fiskeburger","qty":6},{"n":"Burgerbrød","qty":6},{"n":"Salat","qty":1},{"n":"Remulade","qty":1},{"n":"Agurk","qty":1}]'::jsonb),
  ('Vegetarpasta', 'Vegetar', '[{"n":"Pasta","qty":1},{"n":"Cherrytomater","qty":1},{"n":"Squash","qty":1},{"n":"Gryr fløte","qty":1},{"n":"Parmesan","qty":1},{"n":"Hvitløk","qty":1}]'::jsonb)
on conflict (name) do nothing;

-- Middagsmønstre fra kvitteringsanalysen: 8
insert into public.meal_patterns (name, ingredients, hits, rule_text) values
  ('Taco / Tex-Mex', '["Tacolefser/tortilla/lomper","Mais","Tacosaus/salsa","Tacokrydder","Tortillachips/nachos","Tex-Mex kit","Rømme/crème fraîche","Kjøttdeig/karbonadedeig","Avokado","Paprika"]'::jsonb, 66, 'Taco bør foreslås ofte, og ingredienser bør kobles mot tilbud på Coop/MENY/REMA.'),
  ('Spagetti/pasta/lasagne', '["Pasta/spagetti/lasagneplater","Tomater/passata/tomatboks","Kjøttdeig/karbonadedeig","Løk","Revet ost","Parmesan/Grana Padano"]'::jsonb, 39, 'Pasta/spagetti/lasagne er tydelig middagsmønster.'),
  ('Fiskemiddag', '["Laks","Rødspette","Sei","Fiskeburger","Panert fisk","Poteter","Brokkoli","Gulrøtter"]'::jsonb, 32, 'Fisk forekommer i flere former og bør støtte regelen om minst 2 fiskemiddager per uke.'),
  ('Burgere', '["Hamburgere/burgerost","Burgerbrød","Dressing/salater/tilbehør","Ketchup","Sennep","Salat","Søtpotet/søtpotetfries"]'::jsonb, 25, 'Burgere/burgerbrød finnes særlig i Rema/Coop, relevant helgemiddag.'),
  ('Pølser/grill', '["Pølser","Ketchup","Sennep","Dressing/salater/tilbehør","Mais","Grillkjøtt/koteletter/ribs"]'::jsonb, 27, 'Pølser/grillmat er tydelig sesong/helgemønster.'),
  ('Pizza', '["Revet ost","Mozzarella","Salami/spekeskinke","Kokt skinke","Tomater/passata/tomatboks"]'::jsonb, 25, 'Pizza bør være egen middagsmal.'),
  ('Kylling curry/Bali/Bretagne', '["Kylling","Saus/grytepose","Ris"]'::jsonb, 22, 'Kylling + saus/ris er rask middag.'),
  ('Matpakke/pålegg', '["Brød/bakervarer","Knekkebrød/Rugsprø","Kokt skinke","Salami/spekeskinke","Leverpostei","Makrell i tomat","Kaviar","Cottage cheese"]'::jsonb, 49, 'Pålegg/brødvarer bør foreslås ofte basert på historikk.')
on conflict (name) do nothing;
