-- Prisoppdatering fra kvitteringsanalysene (Claude Design, mars–august 2026).
-- Generert av scripts/generate-price-update.py fra tre arbeidsbøker: 186 produkter,
-- 329 normaliseringsregler. Eksisterende varer får oppdatert pris/tellere/signal;
-- navn og kategori på eksisterende varer røres ikke. Kjøres trygt flere ganger.

insert into public.item_catalog
  (name, name_en, category, major_category, is_food, line_count, receipt_count,
   avg_price, price_low, price_high, frequency_sig, primary_store, score)
values
  ('Agurk', 'Cucumber', 'Frukt og grønt', 'Frukt og grønt', true, 14, 11, 40.49, 22.9, 111.6, 'Svært ofte', 'Coop Extra', 39),
  ('Aioli', 'Aioli', 'Saus/tilbehør', 'Krydder og saus', true, 1, 1, 19.9, 19.9, 19.9, '', 'Coop Extra', 3),
  ('Avokado', 'Avocado', 'Frukt og grønt', 'Frukt og grønt', true, 2, 2, 39.65, 29.9, 42.9, 'Ofte', 'Coop Extra', 6),
  ('Baby back ribs', 'Baby back ribs', 'Kjøtt/grill', 'Kjøtt', true, 1, 1, 135.0, 135.0, 135.0, '', null, 3),
  ('Bacon', 'Bacon', 'Kjøtt', 'Kjøtt', true, 4, 3, 63.83, 31.73, 127.8, 'Ofte', 'Coop Extra', 11),
  ('Bananer', 'Bananas', 'Frukt og grønt', 'Frukt og grønt', true, 2, 2, 27.25, 24.4, 31.79, 'Ofte', 'Coop Extra', 6),
  ('Barneplaster Sonic 20Stk Salvequick', 'Barneplaster Sonic 20Stk Salvequick', 'Non-food/household', 'Hus og hjem', false, 1, 1, 32.9, 32.9, 32.9, '', 'Meny', 3),
  ('Basilikum', 'Basil', 'Frukt og grønt', 'Frukt og grønt', true, 2, 2, 18.9, 18.9, 18.9, '', 'Coop Extra', 6),
  ('Blomkål', 'Cauliflower', 'Frukt og grønt', 'Frukt og grønt', true, 2, 2, 38.78, null, 79.6, '', 'Coop Extra', 6),
  ('Blåbær', 'Blueberries', 'Frukt og grønt', 'Frukt og grønt', true, 3, 3, 47.52, 38.94, 59.9, 'Ofte', 'Coop Extra', 9),
  ('Bretagne saus', 'Bretagne sauce', 'Saus/tilbehør', 'Krydder og saus', true, 2, 2, 32.7, null, 51.0, 'Ofte', null, 6),
  ('Bringebær', 'Raspberries', 'Frukt og grønt', 'Frukt og grønt', true, 1, 1, 44.9, 44.9, 44.9, '', 'Coop Extra', 3),
  ('Brokkoli', 'Broccoli', 'Frukt og grønt', 'Frukt og grønt', true, 6, 6, 19.88, 8.94, 44.7, 'Svært ofte', 'Coop Extra', 18),
  ('Brunost', 'Brown cheese', 'Meieri', 'Meieri', true, 1, 1, 56.4, 56.4, 56.4, 'Ofte', 'Coop Extra', 3),
  ('Brød', 'Bread', 'Brød/knekkebrød', 'Brød og korn', true, 11, 7, 32.68, 25.9, 101.8, 'Ofte', 'Coop Extra', 29),
  ('Buljong', 'Bouillon/stock cubes', 'Middagstilbehør', 'Annet', true, 5, 2, 25.27, 18.2, 35.8, 'Ofte', 'Coop Extra', 12),
  ('Burgerbrød', 'Burger buns', 'Brød/knekkebrød', 'Brød og korn', true, 6, 5, 27.49, 22.9, 45.8, 'Ofte', 'Coop Extra', 17),
  ('Bzerepose Papir Meny 26] 32X17X40 Cm', 'Bzerepose Papir Meny 26] 32X17X40 Cm', 'Non-food/household', 'Hus og hjem', false, 1, 1, 9.0, 9.0, 9.0, '', 'Meny', 3),
  ('Bzerepose Pr Stk', 'Bzerepose Pr Stk', 'Non-food/household', 'Hus og hjem', false, 1, 1, 6.75, 6.75, 6.75, '', 'Meny', 3),
  ('Bzereposer 80 %', 'Bzereposer 80 %', 'Non-food/household', 'Hus og hjem', false, 5, 5, 6.75, 6.75, 6.75, 'Ofte', 'Rema 1000', 15),
  ('Bzrepose Papir Meny 26] 32X17X40 Cm', 'Bzrepose Papir Meny 26] 32X17X40 Cm', 'Non-food/household', 'Hus og hjem', false, 2, 2, 6.75, 4.5, 9.0, '', 'Meny', 6),
  ('Bzrepose Pr Stk', 'Bzrepose Pr Stk', 'Non-food/household', 'Hus og hjem', false, 1, 1, 6.75, 6.75, 6.75, '', 'Meny', 3),
  ('Cherrytomater', 'Cherry tomatoes', 'Frukt og grønt', 'Frukt og grønt', true, 1, 1, 16.9, 16.9, 16.9, '', null, 3),
  ('Coop Sweet Potato Fr', null, 'Uklassifisert', 'Annet', true, 1, 1, 31.9, null, 63.8, '', 'Coop Extra', 3),
  ('Cottage cheese', 'Cottage cheese', 'Meieri', 'Meieri', true, 8, 8, 47.93, 46.9, 95.8, 'Svært ofte', 'Coop Extra', 24),
  ('Crispisalat', 'Crisp lettuce', 'Frukt og grønt', 'Frukt og grønt', true, 4, 4, 37.52, 26.9, 83.86, '', 'Coop Extra', 12),
  ('Crème fraîche', 'Crème fraîche', 'Meieri', 'Meieri', true, 2, 2, 30.1, 29.9, 30.5, '', 'Coop Extra', 6),
  ('Curry paste', 'Curry paste', 'Middagstilbehør', 'Annet', true, 1, 1, 29.5, 29.5, 29.5, '', 'Coop Extra', 3),
  ('Def.Men Sham.Cl.&Fr.', 'Def.Men Sham.Cl.&Fr.', 'Non-food/household', 'Hus og hjem', false, 1, 1, 21.15, 21.15, 21.15, '', 'Coop Extra', 3),
  ('Def.Sham.Cl.&H.400Ml', 'Def.Sham.Cl.&H.400Ml', 'Non-food/household', 'Hus og hjem', false, 1, 1, 50.94, 50.94, 50.94, '', 'Coop Extra', 3),
  ('Diverse ikke-mat', 'Misc non-food', 'Ikke-mat', 'Annet', false, 5, 4, 149.96, 49.8, 358.0, '', 'Coop Extra', 14),
  ('Druer', 'Grapes', 'Frukt og grønt', 'Frukt og grønt', true, 1, 1, 29.9, 29.9, 29.9, 'Ofte', 'Coop Extra', 3),
  ('Dusjsåpe', 'Shower gel', 'Hygiene', 'Hus og hjem', false, 2, 2, 35.23, 32.9, 39.9, '', 'Coop Extra', 6),
  ('Egg', 'Eggs', 'Egg', 'Meieri', true, 4, 4, 58.29, 39.9, 79.8, 'Ofte', 'Coop Extra', 12),
  ('Enchilada kit', 'Enchilada kit', 'Tex-Mex', 'Tørrvarer', true, 1, 1, 72.5, 72.5, 72.5, '', null, 3),
  ('Enchilada-kit', 'Enchilada kit', 'Taco/Tex-Mex', 'Tørrvarer', true, 1, 1, 72.5, 72.5, 72.5, '', 'Coop Extra', 3),
  ('Epler', 'Apples', 'Frukt og grønt', 'Frukt og grønt', true, 6, 5, 46.76, 25.2, 59.9, 'Ofte', 'Coop Extra', 17),
  ('Ferdigmiddag tandoori', 'Ready meal, tandoori', 'Ferdigmiddag', 'Frysevarer', true, 1, 1, 81.5, 81.5, 81.5, '', null, 3),
  ('Fiskebuljong', 'Fish stock cubes', 'Buljong', 'Tørrvarer', true, 1, 1, 17.4, null, 34.8, '', null, 3),
  ('Fiskeburger', 'Fish burger', 'Fisk', 'Fisk', true, 1, 1, 91.5, null, 164.7, '', 'Coop Extra', 3),
  ('Fjl Masalamagic Tand', null, 'Uklassifisert', 'Annet', true, 1, 1, 81.5, 81.5, 81.5, '', 'Coop Extra', 3),
  ('Fullkornsspagetti', 'Whole wheat spaghetti', 'Tørrvarer', 'Tørrvarer', true, 5, 5, 34.57, 12.7, 119.8, 'Ofte', 'Coop Extra', 15),
  ('Fullkornswraps', 'Whole wheat wraps', 'Taco/Tex-Mex', 'Tørrvarer', true, 1, 1, 14.9, null, 44.7, '', null, 3),
  ('Grana Padano', 'Grana Padano', 'Ost', 'Ost og pålegg', true, 1, 1, 38.6, 38.6, 38.6, '', null, 3),
  ('Gresk yoghurt', 'Greek yoghurt', 'Meieri', 'Meieri', true, 1, 1, 45.9, 45.9, 45.9, '', null, 3),
  ('Grillribbe', 'Seasoned pork ribs', 'Kjøtt/grill', 'Kjøtt', true, 1, 1, 80.0, null, 160.0, '', null, 3),
  ('Grillsett 2 Deler', 'Grillsett 2 Deler', 'Non-food/household', 'Hus og hjem', false, 1, 1, 99.0, 99.0, 99.0, '', 'Coop Extra', 3),
  ('Gryr fløte', 'Plant-based cooking cream', 'Melkefritt', 'Meieri', true, 2, 2, 25.9, null, 103.6, 'Ofte', null, 6),
  ('Gryr fløteerstatning', 'Plant-based cream substitute', 'Melkefritt/vegansk', 'Meieri', true, 5, 5, 25.62, null, 103.6, 'Ofte', 'Coop Extra', 15),
  ('Grønnsaksbuljong', 'Vegetable stock cubes', 'Buljong', 'Tørrvarer', true, 1, 1, 17.4, null, 34.8, '', null, 3),
  ('Gulost', 'Yellow cheese, Norvegia', 'Ost', 'Ost og pålegg', true, 6, 4, 60.7, 60.5, 236.28, 'Svært ofte', null, 16),
  ('Gulrøtter', 'Carrots', 'Frukt og grønt', 'Frukt og grønt', true, 6, 6, 24.91, 9.9, 47.8, 'Svært ofte', 'Coop Extra', 18),
  ('Hakkede tomater med hvitløk', 'Chopped tomatoes with garlic', 'Hermetisk/tomat', 'Tørrvarer', true, 2, 2, 14.35, null, 31.0, 'Ofte', null, 6),
  ('Hakkede tomater med urter', 'Chopped tomatoes with herbs', 'Hermetisk/tomat', 'Tørrvarer', true, 2, 2, 13.9, null, 29.8, 'Ofte', null, 6),
  ('Hamburgerbrød', 'Burger buns', 'Brød/burger', 'Brød og korn', true, 2, 1, 25.4, 22.9, 27.9, 'Ofte', null, 5),
  ('Hamburgere', 'Burgers', 'Kjøtt', 'Kjøtt', true, 3, 3, 137.17, 99.0, 149.9, 'Ofte', 'Coop Extra', 9),
  ('Handlenett Extra', 'Handlenett Extra', 'Non-food/household', 'Hus og hjem', false, 1, 1, 20.0, 20.0, 20.0, '', 'Coop Extra', 3),
  ('Havredrikk', 'Oat drink', 'Melkefritt/vegansk', 'Meieri', true, 1, 1, 34.5, 34.5, 34.5, '', 'Coop Extra', 3),
  ('Havredrikk sjokolade', 'Chocolate oat drink', 'Melkefritt', 'Meieri', true, 1, 1, 34.5, 34.5, 34.5, '', null, 3),
  ('Havremelk', 'Oat milk', 'Melkefritt', 'Meieri', true, 4, 4, 57.5, 34.5, 79.79, 'Ofte', 'Meny', 12),
  ('Hvitløksbaguetter', 'Garlic baguettes', 'Brød/knekkebrød', 'Brød og korn', true, 1, 1, 21.9, null, 43.8, 'Ofte', 'Coop Extra', 3),
  ('Håndsåpe', 'Hand soap', 'Hygiene', 'Hus og hjem', false, 2, 2, 22.9, 22.9, 68.7, '', 'Coop Extra', 6),
  ('Ibux Tabl.200Mg', 'Ibux Tabl.200Mg', 'Non-food/household', 'Hus og hjem', false, 1, 1, 61.5, 61.5, 61.5, '', 'Coop Extra', 3),
  ('Is', 'Ice cream', 'Snacks/godteri', 'Snacks', true, 8, 6, 67.29, 24.9, 86.0, 'Svært ofte', 'Coop Extra', 22),
  ('Isbergsalat', 'Iceberg lettuce', 'Frukt og grønt', 'Frukt og grønt', true, 5, 5, 27.27, 14.9, 36.9, 'Ofte', 'Coop Extra', 15),
  ('Iskrem', 'Gelato ice cream', 'Is/dessert', 'Frysevarer', true, 1, 1, 78.5, 78.5, 78.5, '', null, 3),
  ('Jordbær', 'Strawberries', 'Frukt og grønt', 'Frukt og grønt', true, 11, 11, 52.5, 24.9, 99.8, 'Svært ofte', 'Coop Extra', 33),
  ('Jordbærsyltetøy', 'Strawberry jam, Skweezy', 'Syltetøy', 'Ost og pålegg', true, 2, 2, 29.95, null, 120.0, 'Ofte', null, 6),
  ('Juice', 'Juice', 'Drikke', 'Drikke', true, 1, 1, 19.9, 19.9, 19.9, '', 'Meny', 3),
  ('Kalkunkorv', 'Turkey sausage', 'Pølser', 'Kjøtt', true, 1, 1, 50.9, 50.9, 50.9, '', null, 3),
  ('Kaviar', 'Cod roe spread', 'Pålegg', 'Ost og pålegg', true, 1, 1, 43.5, 43.5, 43.5, 'Ofte', 'Coop Extra', 3),
  ('Ketchup', 'Ketchup', 'Saus', 'Krydder og saus', true, 5, 5, 49.1, 33.9, 61.4, 'Ofte', 'Coop Extra', 15),
  ('Ketchup, Heinz', 'Ketchup, Heinz', 'Saus/tilbehør', 'Krydder og saus', true, 4, 4, 49.17, 52.5, 61.4, '', 'Coop Extra', 12),
  ('Kiwi', 'Kiwi', 'Frukt og grønt', 'Frukt og grønt', true, 3, 3, 36.03, 39.6, 119.0, 'Ofte', 'Coop Extra', 9),
  ('Kjøttbuljong', 'Beef stock cubes', 'Buljong', 'Tørrvarer', true, 1, 1, 29.1, 29.1, 29.1, '', null, 3),
  ('Kjøttdeig', 'Minced meat', 'Kjøtt', 'Kjøtt', true, 4, 4, 66.57, null, 279.6, 'Ofte', 'Coop Extra', 12),
  ('Kleenex Lommetorkle Allergy Comf.8X9Stk', 'Kleenex Lommetorkle Allergy Comf.8X9Stk', 'Non-food/household', 'Hus og hjem', false, 1, 1, 39.9, 39.9, 39.9, '', 'Meny', 3),
  ('Kokosmelk', 'Coconut milk', 'Tørrvarer', 'Tørrvarer', true, 1, 1, 20.5, null, 41.0, '', 'Coop Extra', 3),
  ('Kokt skinke', 'Cooked ham', 'Pålegg', 'Ost og pålegg', true, 5, 5, 35.59, 20.0, 90.6, 'Ofte', 'Coop Extra', 15),
  ('Krone-is', 'Ice cream cone', 'Is/dessert', 'Frysevarer', true, 2, 2, 74.5, 71.5, 77.5, 'Ofte', null, 6),
  ('Krone-is jordbær', 'Strawberry ice cream cone', 'Is/dessert', 'Frysevarer', true, 1, 1, 24.9, 24.9, 24.9, '', null, 3),
  ('Krone-is sjokolade', 'Chocolate ice cream cone', 'Is/dessert', 'Frysevarer', true, 1, 1, 24.9, 24.9, 24.9, '', null, 3),
  ('Kylling', 'Chicken', 'Kylling', 'Kjøtt', true, 9, 7, 131.35, 33.74, 254.4, 'Svært ofte', 'Meny', 25),
  ('Kyllingbuljong', 'Chicken stock cubes', 'Buljong', 'Tørrvarer', true, 2, 2, 18.05, 18.2, 35.8, 'Ofte', null, 6),
  ('Kyllingfilet', 'Chicken breast fillet', 'Kylling', 'Kjøtt', true, 1, 1, 119.0, null, 238.0, 'Ofte', null, 3),
  ('Kålrot', 'Swede/rutabaga', 'Frukt og grønt', 'Frukt og grønt', true, 1, 1, 31.4, 31.4, 31.4, '', 'Coop Extra', 3),
  ('Laks', 'Salmon', 'Fisk', 'Fisk', true, 3, 3, 126.85, 92.9, 189.8, 'Svært ofte', 'Coop Extra', 9),
  ('Laksefilet', 'Salmon fillet', 'Fisk', 'Fisk', true, 3, 3, 87.57, 92.9, 189.8, '', 'Coop Extra', 9),
  ('Lambi Toa.Papir 24Pk', 'Lambi Toa.Papir 24Pk', 'Non-food/household', 'Hus og hjem', false, 3, 3, 128.67, 99.0, 143.5, 'Ofte', 'Coop Extra', 9),
  ('Lano Dusjsape 250Ml', 'Lano Dusjsape 250Ml', 'Non-food/household', 'Hus og hjem', false, 1, 1, 32.9, 32.9, 32.9, '', 'Coop Extra', 3),
  ('Lasagneplater', 'Lasagne sheets', 'Tørrvarer', 'Tørrvarer', true, 2, 2, 41.9, null, 83.8, 'Ofte', 'Coop Extra', 6),
  ('Lettmelk', 'Low-fat milk', 'Meieri', 'Meieri', true, 7, 7, 29.67, 21.9, 33.9, 'Ofte', 'Coop Extra', 21),
  ('Lettrømme', 'Sour cream', 'Meieri', 'Meieri', true, 4, 4, 23.57, 22.9, 47.8, 'Ofte', 'Coop Extra', 12),
  ('Leverpostei', 'Liver pâté', 'Pålegg', 'Ost og pålegg', true, 2, 2, 15.4, 15.4, 15.4, 'Ofte', 'Coop Extra', 6),
  ('Lime', 'Lime', 'Frukt og grønt', 'Frukt og grønt', true, 3, 3, 5.86, 4.04, 7.54, 'Ofte', 'Coop Extra', 9),
  ('Linea Bokmerker', 'Linea Bokmerker', 'Non-food/household', 'Hus og hjem', false, 1, 1, 49.8, 49.8, 49.8, '', 'Coop Extra', 3),
  ('Løk', 'Onion', 'Frukt og grønt', 'Frukt og grønt', true, 12, 9, 24.98, 11.9, 46.9, 'Svært ofte', 'Coop Extra', 33),
  ('Mais', 'Corn', 'Taco/Tex-Mex', 'Tørrvarer', true, 6, 6, 36.74, 26.5, 99.8, 'Svært ofte', 'Coop Extra', 18),
  ('Makrell i tomat', 'Mackerel in tomato', 'Pålegg', 'Ost og pålegg', true, 14, 6, 44.57, 19.9, 124.5, 'Svært ofte', 'Coop Extra', 34),
  ('Mel', 'Flour', 'Baking', 'Tørrvarer', true, 2, 2, 21.3, 18.5, 26.9, '', 'Coop Extra', 6),
  ('Melk', 'Milk', 'Meieri', 'Meieri', true, 8, 8, 35.46, 21.9, 49.9, 'Svært ofte', 'Coop Extra', 24),
  ('Mikropopcorn', 'Microwave popcorn', 'Snacks', 'Snacks', true, 1, 1, 20.5, 20.5, 20.5, '', null, 3),
  ('Mozzarella', 'Mozzarella', 'Meieri', 'Meieri', true, 6, 4, 38.43, 30.4, 65.8, 'Ofte', 'Coop Extra', 16),
  ('Muskat', 'Nutmeg', 'Krydder', 'Krydder og saus', true, 1, 1, 34.7, 34.7, 34.7, '', 'Coop Extra', 3),
  ('Nugatti', 'Chocolate spread', 'Pålegg', 'Ost og pålegg', true, 3, 3, 39.73, 39.4, 39.9, 'Ofte', 'Coop Extra', 9),
  ('Opptenningsposer 100Stk Burner', 'Opptenningsposer 100Stk Burner', 'Non-food/household', 'Hus og hjem', false, 1, 1, 89.0, 89.0, 89.0, '', 'Meny', 3),
  ('Palmolive Deo', 'Palmolive Deo', 'Non-food/household', 'Hus og hjem', false, 1, 1, 24.9, 24.9, 24.9, '', 'Rema 1000', 3),
  ('Panert fisk', 'Breaded fish', 'Fisk', 'Fisk', true, 1, 1, 49.9, 49.9, 49.9, '', 'Coop Extra', 3),
  ('Panert rødspette', 'Breaded plaice', 'Fisk', 'Fisk', true, 2, 2, 100.95, 100.9, 202.0, '', 'Coop Extra', 6),
  ('Pant', null, 'Pant/ikke-mat', 'Annet', false, 14, 8, 2.5, 2.0, 20.0, 'Svært ofte', 'Coop Extra', 36),
  ('Paprika', 'Bell pepper', 'Frukt og grønt', 'Frukt og grønt', true, 18, 16, 32.38, 16.05, 54.9, 'Svært ofte', 'Coop Extra', 52),
  ('Pastaskruer fullkorn', 'Whole wheat fusilli', 'Pasta', 'Tørrvarer', true, 1, 1, 27.9, 27.9, 27.9, '', null, 3),
  ('Peanøttsmør', 'Peanut butter', 'Pålegg', 'Ost og pålegg', true, 1, 1, 39.9, 39.9, 39.9, '', 'Coop Extra', 3),
  ('Pepperoni', 'Pepperoni', 'Pålegg/pizza', 'Ost og pålegg', true, 3, 3, 41.71, 34.9, 61.14, '', 'Coop Extra', 9),
  ('Pinsa', 'Pinsa pizza base', 'Pizza', 'Frysevarer', true, 1, 1, 29.9, null, 149.5, '', null, 3),
  ('Pizzabunn', 'Pizza base', 'Pizza', 'Frysevarer', true, 2, 2, 50.95, null, 69.9, 'Ofte', null, 6),
  ('Pizzabunn fullkorn', 'Whole wheat pizza base', 'Pizza', 'Frysevarer', true, 1, 1, 19.9, null, 39.8, '', null, 3),
  ('Pizzafyll', 'Pizza filling mix, Toro', 'Pizza/pose', 'Frysevarer', true, 2, 1, 27.9, null, 59.8, '', null, 5),
  ('Pizzamel', 'Pizza flour', 'Baking', 'Tørrvarer', true, 1, 1, 26.9, 26.9, 26.9, 'Ofte', 'Coop Extra', 3),
  ('Pizzasaus', 'Pizza sauce', 'Pizza', 'Frysevarer', true, 1, 1, 28.5, 28.5, 28.5, 'Ofte', 'Coop Extra', 3),
  ('Plaster Aqua Block 16Stk Salvequick', 'Plaster Aqua Block 16Stk Salvequick', 'Non-food/household', 'Hus og hjem', false, 1, 1, 59.9, 59.9, 59.9, '', 'Meny', 3),
  ('Plastpose', 'Plastic bag', 'Pose/emballasje', 'Annet', false, 5, 5, 7.88, 6.75, 13.5, 'Ofte', 'Coop Extra', 15),
  ('Popcorn', 'Popcorn', 'Snacks', 'Snacks', true, 2, 2, 20.45, 16.5, 25.9, '', 'Coop Extra', 6),
  ('Poteter', 'Potatoes', 'Frukt og grønt', 'Frukt og grønt', true, 17, 12, 50.27, 13.59, 99.0, 'Svært ofte', 'Coop Extra', 46),
  ('Potetgull', 'Potato chips', 'Snacks', 'Snacks', true, 2, 1, 24.9, 24.9, 24.9, 'Ofte', null, 5),
  ('Potetsalat', 'Potato salad', 'Tilbehør/grill', 'Tørrvarer', true, 2, 2, 33.2, 28.5, 37.9, 'Ofte', null, 6),
  ('Pærer', 'Pears', 'Frukt og grønt', 'Frukt og grønt', true, 2, 2, 44.5, 42.57, 51.23, 'Ofte', 'Coop Extra', 6),
  ('Pølser', 'Sausages', 'Kjøtt', 'Kjøtt', true, 7, 6, 72.2, 20.4, 99.8, 'Svært ofte', 'Coop Extra', 20),
  ('Red curry paste', 'Red curry paste', 'Asiatisk/krydder', 'Tørrvarer', true, 1, 1, 29.5, 29.5, 29.5, '', null, 3),
  ('Repsils', 'Throat lozenges', 'Helse/apotek', 'Hus og hjem', false, 1, 1, 59.9, 59.9, 59.9, '', null, 3),
  ('Repsils Hon.&Sit.56G', 'Repsils Hon.&Sit.56G', 'Non-food/household', 'Hus og hjem', false, 1, 1, 59.9, 59.9, 59.9, '', 'Coop Extra', 3),
  ('Revet ost', 'Grated cheese', 'Meieri', 'Meieri', true, 4, 4, 74.64, 59.9, 119.8, 'Ofte', 'Coop Extra', 12),
  ('Ricol.Br.Bær Sitr.M.', null, 'Uklassifisert', 'Annet', true, 1, 1, 29.9, 29.9, 29.9, '', 'Coop Extra', 3),
  ('Ricola', 'Throat lozenges', 'Helse/apotek', 'Hus og hjem', false, 2, 1, 29.9, 29.9, 29.9, '', null, 5),
  ('Ricola Original', 'Ricola Original', 'Non-food/household', 'Hus og hjem', false, 1, 1, 29.9, 29.9, 29.9, '', 'Coop Extra', 3),
  ('Ris', 'Rice', 'Tørrvarer', 'Tørrvarer', true, 11, 9, 56.0, 23.9, 87.4, 'Svært ofte', 'Coop Extra', 31),
  ('Rosiner', 'Raisins', 'Tørrvarer', 'Tørrvarer', true, 1, 1, 24.4, 24.4, 24.4, 'Ofte', 'Coop Extra', 3),
  ('Ruccola', 'Rocket / arugula', 'Salat', 'Frukt og grønt', true, 2, 2, 14.95, 14.9, 15.0, 'Svært ofte', 'Coop Extra', 6),
  ('Rugsprø', 'Rye crispbread', 'Knekkebrød', 'Brød og korn', true, 3, 3, 16.4, null, 58.2, 'Ofte', null, 9),
  ('Rødbetsalat', 'Beetroot salad', 'Pålegg', 'Ost og pålegg', true, 1, 1, 32.5, 32.5, 32.5, '', 'Coop Extra', 3),
  ('Rødspette', 'Plaice', 'Fisk', 'Fisk', true, 2, 2, 134.6, 100.9, 202.0, 'Ofte', 'Coop Extra', 6),
  ('S.A.G. Gm.Dags.Surk.', null, 'Uklassifisert', 'Annet', true, 1, 1, 20.0, 20.0, 20.0, '', 'Coop Extra', 3),
  ('Salami', 'Salami', 'Pålegg', 'Ost og pålegg', true, 8, 7, 64.15, 38.1, 123.8, 'Ofte', 'Coop Extra', 23),
  ('Salat', 'Salad', 'Salat', 'Frukt og grønt', true, 3, 3, 50.69, 26.9, 90.28, 'Ofte', 'Coop Extra', 9),
  ('Salatbar', 'Salad bar', 'Ferdigmat', 'Frysevarer', true, 1, 1, 90.28, 90.28, 90.28, '', 'Coop Extra', 3),
  ('Sei', 'Saithe / coalfish', 'Fisk', 'Fisk', true, 2, 1, 32.9, 28.9, 36.9, 'Ofte', 'Coop Extra', 5),
  ('Seifilet', 'Saithe fillet', 'Fisk', 'Fisk', true, 2, 1, 32.9, 28.9, 36.9, '', 'Coop Extra', 5),
  ('Sennep', 'Mustard, Bergbys', 'Saus', 'Krydder og saus', true, 2, 2, 26.9, 23.9, 29.9, 'Ofte', 'Meny', 6),
  ('Sitron', 'Lemon', 'Frukt og grønt', 'Frukt og grønt', true, 1, 1, 21.23, 6.89, null, '', 'Coop Extra', 3),
  ('Sjamp. X-Tra 250G', 'Sjamp. X-Tra 250G', 'Non-food/household', 'Hus og hjem', false, 1, 1, 10.14, 10.14, 10.14, '', 'Coop Extra', 3),
  ('Sjampinjong', 'Mushrooms', 'Frukt og grønt', 'Frukt og grønt', true, 1, 1, 10.14, 10.14, 10.14, '', null, 3),
  ('Sjokade', 'Chocolate spread', 'Pålegg', 'Ost og pålegg', true, 1, 1, 36.9, 36.9, 36.9, '', 'Coop Extra', 3),
  ('Sjokoladepålegg', 'Chocolate spread', 'Pålegg', 'Ost og pålegg', true, 6, 6, 38.82, 36.9, 39.9, 'Svært ofte', 'Coop Extra', 18),
  ('Snackgulrøtter', 'Snack carrots', 'Frukt og grønt', 'Frukt og grønt', true, 1, 1, 9.9, 9.9, 9.9, '', null, 3),
  ('Solsikkekjerner', 'Sunflower seeds', 'Tørrvarer', 'Tørrvarer', true, 1, 1, 23.9, 23.9, 23.9, '', 'Coop Extra', 3),
  ('Sorbet-is', 'Mango sorbet sticks', 'Is/dessert', 'Frysevarer', true, 1, 1, 29.9, 29.9, 29.9, '', null, 3),
  ('Soyamelk uten sukker', 'Unsweetened soy milk', 'Melkefritt/vegansk', 'Meieri', true, 7, 5, 39.65, 29.9, 89.7, 'Ofte', 'Coop Extra', 19),
  ('Spaghetti à la Capri', 'Spaghetti à la Capri', 'Ferdigmiddag/pasta', 'Frysevarer', true, 1, 1, 59.9, null, 119.8, '', null, 3),
  ('Spareribs', 'Spareribs', 'Kjøtt/grill', 'Kjøtt', true, 1, 1, 150.0, 150.0, 150.0, '', null, 3),
  ('Sprøbakte crispies', 'Crispy breaded pieces', 'Frysevare/ukjent', 'Frysevarer', true, 1, 1, 41.93, null, 83.86, '', null, 3),
  ('Sukker', 'Sugar', 'Baking', 'Tørrvarer', true, 1, 1, 35.4, 35.4, 35.4, 'Ofte', 'Coop Extra', 3),
  ('Svinekoteletter', 'Pork chops', 'Kjøtt', 'Kjøtt', true, 1, 1, 119.0, null, 163.75, '', null, 3),
  ('Sweet chili-saus', 'Sweet chili sauce', 'Saus/tilbehør', 'Krydder og saus', true, 1, 1, 54.9, 54.9, 54.9, '', 'Coop Extra', 3),
  ('Tacokrydder', 'Taco seasoning', 'Taco/Tex-Mex', 'Tørrvarer', true, 2, 2, 23.57, 22.9, 23.9, 'Ofte', 'Coop Extra', 6),
  ('Tacosaus hot', 'Hot taco sauce', 'Taco/Tex-Mex', 'Tørrvarer', true, 1, 1, 21.9, 21.9, 21.9, '', null, 3),
  ('Telys Gullk.8T 50Stk', 'Telys Gullk.8T 50Stk', 'Non-food/household', 'Hus og hjem', false, 1, 1, 97.9, 97.9, 97.9, '', 'Coop Extra', 3),
  ('Tex-Mex kit', 'Tex-Mex kit', 'Taco/Tex-Mex', 'Tørrvarer', true, 4, 4, 49.8, 39.9, 72.5, 'Ofte', 'Meny', 12),
  ('Toalettpapir', 'Toilet paper', 'Hus og hjem', 'Hus og hjem', false, 3, 3, 125.7, 99.0, 143.5, 'Ofte', 'Coop Extra', 9),
  ('Tomater', 'Tomatoes', 'Frukt og grønt', 'Frukt og grønt', true, 8, 7, 27.85, 16.9, 55.8, 'Ofte', 'Coop Extra', 23),
  ('Tomatpuré', 'Tomato purée', 'Tørrvarer', 'Tørrvarer', true, 1, 1, 44.5, 44.5, 44.5, '', 'Coop Extra', 3),
  ('Tomatsuppe', 'Tomato soup', 'Middagstilbehør', 'Annet', true, 2, 2, 18.96, null, 46.06, 'Ofte', 'Coop Extra', 6),
  ('Toro Bali kyllinggryte', 'Toro Bali chicken casserole', 'Middagstilbehør', 'Annet', true, 1, 1, 24.43, null, 48.86, '', 'Coop Extra', 3),
  ('Toro Bretagnesaus', 'Toro Bretagne sauce', 'Middagstilbehør', 'Annet', true, 4, 4, 33.96, null, 55.86, '', 'Coop Extra', 12),
  ('Tortillachips', 'Tortilla chips', 'Taco/Tex-Mex', 'Tørrvarer', true, 1, 1, 41.9, 41.9, 41.9, '', null, 3),
  ('Tortillalefser', 'Tortilla wraps', 'Taco/Tex-Mex', 'Tørrvarer', true, 1, 1, 24.5, 24.5, 24.5, '', null, 3),
  ('Tritan Drikkeflaske', 'Tritan Drikkeflaske', 'Non-food/household', 'Hus og hjem', false, 1, 1, 358.0, 358.0, 358.0, '', 'Coop Extra', 3),
  ('Turshorts Ekkertind', 'Turshorts Ekkertind', 'Non-food/household', 'Hus og hjem', false, 1, 1, 349.0, 349.0, 349.0, '', 'Coop Extra', 3),
  ('Tørrgjær', 'Dry yeast', 'Baking', 'Tørrvarer', true, 1, 1, 19.4, 19.4, 19.4, '', 'Coop Extra', 3),
  ('Vannmelon', 'Watermelon', 'Frukt og grønt', 'Frukt og grønt', true, 1, 1, 18.41, 18.41, 18.41, '', 'Coop Extra', 3),
  ('Yoghurt', 'Yoghurt', 'Meieri', 'Meieri', true, 8, 6, 41.45, 20.0, 93.66, 'Svært ofte', 'Coop Extra', 22),
  ('Yoghurt naturell', 'Plain yoghurt', 'Meieri', 'Meieri', true, 1, 1, 47.5, 47.5, 47.5, '', null, 3),
  ('Yoghurtbeger skogsbær', 'Forest berry yoghurt cups', 'Meieri/barn', 'Meieri', true, 1, 1, 25.4, 25.4, 25.4, '', null, 3),
  ('Yoghurtbeger vanilje', 'Vanilla yoghurt cups', 'Meieri/barn', 'Meieri', true, 1, 1, 38.5, 24.9, null, '', null, 3),
  ('Zalo Ultra 5Dl', 'Zalo Ultra 5Dl', 'Non-food/household', 'Hus og hjem', false, 1, 1, 33.9, 33.9, 33.9, '', 'Coop Extra', 3),
  ('¤Xtra Serv.Bordp.30Cm', null, 'Uklassifisert', 'Annet', true, 1, 1, 20.5, 20.5, 20.5, '', 'Coop Extra', 3),
  ('Øl', 'Beer', 'Drikke/alkohol', 'Drikke', true, 4, 4, 141.03, 127.6, 199.8, 'Ofte', 'Coop Extra', 12)
on conflict (name) do update set
  -- Ferske kvitteringspriser vinner over gamle seed-priser, men en ny pris
  -- langt utenfor den gamle (enhets-/mengdeforvirring) forkastes.
  avg_price     = case
                    when excluded.avg_price is null then item_catalog.avg_price
                    when item_catalog.avg_price is null then excluded.avg_price
                    when excluded.avg_price between item_catalog.avg_price * 0.4 and item_catalog.avg_price * 2.5
                      then excluded.avg_price
                    else item_catalog.avg_price
                  end,
  price_low     = least(coalesce(nullif(item_catalog.price_low, 0), excluded.price_low), coalesce(excluded.price_low, item_catalog.price_low)),
  price_high    = greatest(coalesce(item_catalog.price_high, excluded.price_high), coalesce(excluded.price_high, item_catalog.price_high)),
  line_count    = greatest(item_catalog.line_count, excluded.line_count),
  receipt_count = greatest(item_catalog.receipt_count, excluded.receipt_count),
  score         = greatest(item_catalog.score, excluded.score),
  frequency_sig = case when excluded.frequency_sig <> '' then excluded.frequency_sig else item_catalog.frequency_sig end,
  primary_store = coalesce(excluded.primary_store, item_catalog.primary_store),
  name_en       = coalesce(item_catalog.name_en, excluded.name_en);

-- Rydd opp gamle inkonsistenser i hele katalogen: lav ≤ snitt ≤ høy,
-- og 0-priser behandles som ukjente.
update public.item_catalog set
  price_low  = least(coalesce(nullif(price_low, 0), avg_price), avg_price),
  price_high = greatest(coalesce(nullif(price_high, 0), avg_price), avg_price)
where avg_price is not null;

insert into public.norm_rules (from_text, to_text) values
  ('AGURK STK', 'Agurk'),
  ('ALPRO SOYADRI', 'Soyamelk uten sukker, Alpro'),
  ('ALPRO SOYADRI.USØTET', 'Soyamelk uten sukker'),
  ('Avocado / advokado / advoado', 'Avokado'),
  ('AVOKADO', 'Avokado, Modnet 2-pk'),
  ('AVOKADO MODNET 2PK', 'Avokado'),
  ('BABY BACK RIBS', 'Baby back ribs, Coop'),
  ('BANAN', 'Bananer, X-tra'),
  ('BANAN X-TRA KG', 'Bananer'),
  ('BARIL.FULLK.SPAGHET.', 'Fullkornsspagetti'),
  ('BARILLA LASAGNE', 'Lasagneplater, Barilla'),
  ('BARILLA LASAGNE 500G', 'Lasagneplater'),
  ('BASILIK', 'Basilikum, Frisk urt'),
  ('BJERKE HVITLØK RØMME', 'Hvitløk/rømmedressing'),
  ('BLOMKÅL STK', 'Blomkål'),
  ('BRETAGNESAUS', 'Bretagne saus, Toro familiepakke'),
  ('Broccoli', 'Brokkoli'),
  ('BROKKOLI STK', 'Brokkoli'),
  ('Burger / burgere', 'Hamburgere'),
  ('BURGERBR', 'Hamburgerbrød, Coop grov'),
  ('Burgerbrød', 'Hamburgerbrød'),
  ('BÆR BLÅBÆR 400G', 'Blåbær'),
  ('BÆR BRINGEBÆR', 'Bringebær, 225 g'),
  ('BÆR BRINGEBÆR 225G', 'Bringebær'),
  ('COCA COLA UTS', 'Cola Zero / Coca-Cola uten sukker, Coca-Cola'),
  ('COCA COLA UTS 0.33L', 'Cola/Cola Zero'),
  ('COCA COLA UTS 0.5L', 'Cola/Cola Zero'),
  ('COCA COLA UTS 1.5L', 'Cola/Cola Zero'),
  ('COCA COLA UTS 1.5L F', 'Cola/Cola Zero'),
  ('COCA COLA UTS 10PK', 'Cola/Cola Zero'),
  ('COOP AIOLI M. CHILI', 'Aioli'),
  ('COOP BABY BACK RIBS', 'Grillkjøtt/koteletter/ribs'),
  ('COOP BACON SKI.U.SV.', 'Bacon'),
  ('COOP BURGERBRØD', 'Brød'),
  ('COOP EGG FRITTG', 'Egg, Coop frittgående 18-pk'),
  ('COOP EGG FRITTG 18PK', 'Egg'),
  ('COOP FULLK.WR.L 6STK', 'Tacolefser/nachos/taco'),
  ('COOP FUSILLI FULLK.', 'Fullkornspasta/fusilli'),
  ('COOP GRANA PADANO', 'Parmesan/Grana Padano'),
  ('COOP GRILLFILET', 'Kyllingfilet/grillfilet'),
  ('COOP GRILLFILET BBQ', 'Kyllingfilet/grillfilet'),
  ('COOP GRILLRIBBE KRYD', 'Grillkjøtt/koteletter/ribs'),
  ('COOP GROVBRØD', 'Brød'),
  ('COOP GROVE BURGERBR.', 'Burgerbrød'),
  ('COOP GROVE PØLSEBRØD', 'Pølser'),
  ('COOP HA.TOM.URT.390G', 'Hermetiske tomater/passata'),
  ('COOP HAK.TOM.HVITLØK', 'Hermetiske tomater/passata'),
  ('COOP HAVREGULLBRØD', 'Brød'),
  ('COOP JASMINRIS 2KG', 'Ris'),
  ('COOP JORDBÆRSYL.UTEN', 'Jordbær'),
  ('COOP KOKOSMELK 17-19', 'Kokosmelk'),
  ('COOP KOKT SKINK.100G', 'Kokt skinke'),
  ('COOP KOKT SKINK.250G', 'Kokt skinke'),
  ('COOP KRONE-IS JORDBR', 'Søtsaker/is/sjokolade'),
  ('COOP KRONE-IS SJOKOL', 'Søtsaker/is/sjokolade'),
  ('COOP KYLLINGFI.1000G', 'Kyllingfilet/grillfilet'),
  ('COOP KYLLINGFILET', 'Kyllingfilet/grillfilet'),
  ('COOP MAIS 3PK 450G', 'Mais'),
  ('COOP MAISKOLBE 2PK', 'Mais'),
  ('COOP MICROPOPC.SMØR', 'Popcorn'),
  ('COOP NACHOS CHIPS', 'Tacolefser/nachos/taco'),
  ('COOP NAKKEKOTELETTER', 'Grillkjøtt/koteletter/ribs'),
  ('COOP PEPPERONI', 'Pepperoni, Coop'),
  ('COOP PEPPERONI 100G', 'Pepperoni'),
  ('COOP PINSA', 'Pinsa, Coop'),
  ('COOP PINSA 230G', 'Pizza/pizzatilbehør'),
  ('COOP PIZZAB FULLKORN', 'Pizza/pizzatilbehør'),
  ('COOP POTETSALAT', 'Poteter'),
  ('COOP ROSINER 250G', 'Rosiner'),
  ('COOP SPARERIBS', 'Grillkjøtt/koteletter/ribs'),
  ('COOP SUPERBRØD', 'Brød, Coop Superbrød 750 g'),
  ('COOP SUPERBRØD 750G', 'Brød'),
  ('COOP TORT.CHIPS SALT', 'Chips/snacks'),
  ('COTT.CH', 'Cottage cheese, Mager'),
  ('COTT.CH MAGER 770G', 'Cottage cheese'),
  ('COTT.CHE', 'Cottage cheese, Mager'),
  ('COTT.CHEE MAGER 400G', 'Cottage cheese'),
  ('CRISPY HOT WINGS', 'Crispisalat'),
  ('CRÈME FRAÎCHE', 'Crème fraîche, Tine'),
  ('DEF.DRY.ORIG.200ML', 'Hår-/kroppspleie'),
  ('DEF.MEN MOULD.CLAY', 'Hår-/kroppspleie'),
  ('DEF.MEN SHAM.CL.&FR.', 'Hår-/kroppspleie'),
  ('DEF.SHAM.CL.&H.400ML', 'Hår-/kroppspleie'),
  ('Dopapir', 'Toalettpapir'),
  ('DR.O RIST.PEPPERONI', 'Pepperoni'),
  ('ENCHILADA KIT', 'Enchilada kit, Old El Paso'),
  ('EPLE KANZI KG', 'Epler'),
  ('EXTRA SWEETM', 'Sweet chili/søt saus, Extra'),
  ('EXTRA SWEETM.BOTTLE', 'Sweet chili-saus'),
  ('FINDUS FISH & FUN', 'Fiskepinner/fiskemiddag'),
  ('FISKEBULJONG', 'Fiskebuljong, Maggi'),
  ('FISKEBURGER', 'Fiskeburger, Hyse og torsk'),
  ('FISKEBURGER HYSE&TOR', 'Fiskeburger'),
  ('FJL MASALAMAGIC', 'Ferdigmiddag tandoori, Fjordland Masala Magic'),
  ('FULLK.SPAGHET', 'Fullkornsspagetti, Barilla'),
  ('FULLK.WR', 'Fullkornswraps, Coop'),
  ('FUSILLI FULLK', 'Pastaskruer fullkorn, Coop'),
  ('GELATO IS', 'Iskrem, Gelato Classic'),
  ('GELATO IS CLASSIC', 'Søtsaker/is/sjokolade'),
  ('GILDE BURGER', 'Hamburgere, Gilde 800 g'),
  ('GILDE BURGER 800G', 'Hamburgere'),
  ('GILDE EKTE K.SK.110G', 'Kokt skinke'),
  ('GILDE KJØTTPØLSE', 'Pølser'),
  ('GR.SAKSBULJONG', 'Grønnsaksbuljong, Maggi'),
  ('GR.YOGHURT NAT. 750G', 'Naturell/gresk yoghurt'),
  ('GRANA PADANO', 'Grana Padano, Coop'),
  ('GRIL JUBELSALAM.170G', 'Salami'),
  ('GRIL JUBELSALAM.250G', 'Salami'),
  ('GRILLPØLSE 3X600G', 'Pølser'),
  ('GRILLRIBBE', 'Grillribbe, Coop krydret'),
  ('GRILLSETT 2 DELER', 'Diverse ikke-mat'),
  ('GRILSTAD PEPPERONI', 'Pepperoni'),
  ('GRYR KOKOS/RAPS', 'Gryr fløteerstatning'),
  ('GUDBRANDSDALSOST', 'Brunost'),
  ('Gulerøtter', 'Gulrøtter'),
  ('GULROT', 'Gulrøtter, X-tra / snack / bunt'),
  ('GULROT BUNT POSE', 'Gulrøtter'),
  ('GULROT X-TRA 1KG', 'Gulrøtter'),
  ('HA.TOM.URT', 'Hakkede tomater med urter, Coop'),
  ('HAK.TOM.HVITLØK', 'Hakkede tomater med hvitløk, Coop'),
  ('HAKKEDE TOMATER URTE', 'Hermetiske tomater/passata'),
  ('HAVREDR.SJO', 'Havredrikk sjokolade, Oatly'),
  ('HAVREGULLBRØD', 'Brød, Coop Havregullbrød'),
  ('HEINZ KETCHUP', 'Ketchup, Heinz'),
  ('HEINZ KETCHUP 1KG', 'Ketchup, Heinz'),
  ('HEINZ KETCHUP 570G', 'Ketchup, Heinz'),
  ('HVITLØK 100G', 'Løk'),
  ('Hvitøk', 'Hvitløk'),
  ('IBUX TABL.200MG', 'Apotek/helse'),
  ('IDUN TØRRGJÆR 5PK', 'Tørrgjær'),
  ('ISBERG', 'Isbergsalat, Änglamark'),
  ('ISBERG Änglamark STK', 'Isbergsalat'),
  ('ISBERGSALAT STK', 'Isbergsalat'),
  ('JORDBÆR 500G NO', 'Jordbær'),
  ('JORDBÆRSYLT.MOST 60%', 'Jordbær'),
  ('JUBELSALAM', 'Salami, Grilstad Jubelsalami'),
  ('KALKUNKOR', 'Kalkunkorv, Prior'),
  ('Ketshup / ketshup', 'Ketchup'),
  ('KIMS PAPR.KICK 80G', 'Chips/snacks'),
  ('KIMS PAPRIKA KICK', 'Chips/snacks'),
  ('KIMS SALT CRUNCH', 'Chips/snacks'),
  ('KIMS SALT CRUNCH 80G', 'Chips/snacks'),
  ('KIWI GRØNN', 'Kiwi'),
  ('KIWI GRØNN STK', 'Kiwi'),
  ('KJØTTBULJONG', 'Kjøttbuljong, Maggi'),
  ('KLASSISK POTETSALAT', 'Poteter'),
  ('KOKESJOK.MØRK 46%', 'Søtsaker/is/sjokolade'),
  ('KOKOSMELK', 'Kokosmelk, Coop'),
  ('KOKT SKINK', 'Kokt skinke, Coop'),
  ('KRONE-IS', 'Krone-is, Coop / Cookie Dough / jordbær / sjokolade'),
  ('KRONE-IS COOK.DOUGH', 'Søtsaker/is/sjokolade'),
  ('KRY.URT 8CM BASILIK.', 'Basilikum'),
  ('KYLLINGBULJONG', 'Kyllingbuljong, Maggi'),
  ('KYLLINGFI', 'Kyllingfilet, Coop'),
  ('Kålrabi', 'Kålrot'),
  ('KÅLROT KG', 'Kålrot'),
  ('LAMBI TOA.PAPIR', 'Toalettpapir, Lambi 24-pk'),
  ('LANO DUSJSÅPE', 'Dusjsåpe, Lano'),
  ('LANO DUSJSÅPE 250ML', 'Dusjsåpe'),
  ('LANO HÅNDS.REFILL', 'Håndsåpe'),
  ('Lasansje', 'Lasagne'),
  ('Lefte', 'Lefse / tacolefser'),
  ('LER.PANERT RØDSPETTE', 'Panert rødspette'),
  ('LETTRØM', 'Lettrømme, Tine 17% 300 g'),
  ('LEVERPOSTEI 100G', 'Leverpostei'),
  ('LIME KG', 'Lime'),
  ('LINEA BOKMERKER', 'Diverse ikke-mat'),
  ('LOLLIPOP 12PK', 'Søtsaker/is/sjokolade'),
  ('LØK STRØMPE', 'Løk, 700 g strømpe'),
  ('LØK STRØMPE 700G', 'Løk'),
  ('MAAR.POTETG.PAPRIKA', 'Chips/snacks'),
  ('MAAR.POTETG.SA.&PEP.', 'Chips/snacks'),
  ('MAGGI FISKEBULJONG', 'Buljong'),
  ('MAGGI GR.SAKSBULJONG', 'Buljong'),
  ('MAGGI KJØTTBULJONG', 'Buljong'),
  ('MAGGI KYLLINGBULJONG', 'Buljong'),
  ('MAIS 3PK', 'Mais, Coop 3-pk'),
  ('Makrellitomat / makrel', 'Makrell i tomat'),
  ('MANGO SORBET', 'Sorbet-is, Mango'),
  ('MANGO SORBET STICKS', 'Søtsaker/is/sjokolade'),
  ('MELON VANN DELT KG', 'Vannmelon'),
  ('MICROPOPC', 'Mikropopcorn, Coop smør'),
  ('MILLS KAVIAR', 'Kaviar, Mills tube'),
  ('MILLS KAVIAR TUBE', 'Kaviar'),
  ('MILLS PEANUT BUTTER', 'Peanøttsmør'),
  ('MILLS RØDBETSALAT', 'Rødbetsalat'),
  ('Mozarella', 'Mozzarella'),
  ('MUSKATNØTT', 'Muskat, Santa Maria malt'),
  ('MUTTI TOM.KNUST 400G', 'Hermetiske tomater/passata, Mutti'),
  ('NORA JORDBÆRSY', 'Jordbærsyltetøy, Nora'),
  ('NORA JORDBÆRSY. 400G', 'Jordbær'),
  ('NORVEGIA DUOPACK', 'Gulost/Norvegia'),
  ('Norwegia', 'Norvegia'),
  ('NUGATTI', 'Nugatti, 500 g'),
  ('NUGATTI 500G', 'Nugatti'),
  ('OATLY HAVREDR.SJO.1L', 'Havredrikk'),
  ('OBOY POSE 1100G', 'Søtsaker/is/sjokolade'),
  ('OEP ENCHILADA KIT', 'Enchilada-kit'),
  ('OEP TORTIL', 'Tortillalefser, Old El Paso'),
  ('OEP TORTIL.MED.8STK', 'Tacolefser/nachos/taco'),
  ('PALM.DUSJS.MEN BLUE', 'Dusjsåpe'),
  ('PAPRIKA', 'Paprika, X-tra'),
  ('PAPRIKA SNACK 300G', 'Paprika'),
  ('PAPRIKA X-TRA KG', 'Paprika'),
  ('PEANUT BUTTER', 'Peanøttsmør, Mills'),
  ('PEPP.PIZZABUNN', 'Pizzabunn, Peppes'),
  ('PEPP.PIZZABUNN 550G', 'Pizza/pizzatilbehør'),
  ('PEPPERONI', 'Pepperoni, Coop'),
  ('Permesan', 'Parmesanost'),
  ('PINK LADY', 'Epler, Pink Lady 6-pk'),
  ('PINK LADY EPLER 6PK', 'Epler'),
  ('PIZZA SAUS', 'Pizzasaus, Änglamark'),
  ('PIZZAB FULLKORN', 'Pizzabunn fullkorn, Coop'),
  ('PIZZAFYLL MEXIC', 'Pizzafyll, Toro Mexican'),
  ('PIZZAFYLL TO&LØ', 'Pizzafyll, Toro tomat og løk'),
  ('PLASTPOSE', 'Pose/handlenett'),
  ('POLLY PEANØTTER 80G', 'Nøtter/chilinøtter'),
  ('POTET RØD 2KG NO', 'Poteter'),
  ('POTET X-TRA', 'Poteter, X-tra 4 kg'),
  ('POTET X-TRA 4KG', 'Poteter'),
  ('POTETSALAT', 'Potetsalat, Coop/Klassisk'),
  ('PRIOR KALKUNKOR.450G', 'Pølser'),
  ('Q F.YOG.VANILJE 800G', 'Yoghurt'),
  ('Q-MELK LE', 'Lettmelk, Q-Meieriene 0,5% 1,75 L'),
  ('Q-MELK LE.0.5% 1.75L', 'Lettmelk'),
  ('QD PIZZABUNN', 'Pizzabunn, Q/QD 2-pk'),
  ('QD PIZZABUNN 2PK', 'Pizza/pizzatilbehør'),
  ('RED CURRYPASTE', 'Red curry paste, Santa Maria'),
  ('REGAL PIZZAMEL 1KG', 'Pizzamel'),
  ('REGAL SAM.HVETE GROV', 'Mel'),
  ('REPSILS', 'Repsils, Honning/sitron'),
  ('REPSILS HON.&SIT.56G', 'Apotek/helse'),
  ('RICOL', 'Ricola'),
  ('RICOLA ORIGINAL', 'Cola/Cola Zero'),
  ('RISTOR. SPECIALE 2PK', 'Pizza/pizzatilbehør'),
  ('RISTOR.MOZZAREL.2PK', 'Pizza/pizzatilbehør'),
  ('RUCCOLA 65G', 'Cola/Cola Zero'),
  ('Ruccula', 'Ruccola'),
  ('RØD DRUE 500G', 'Druer'),
  ('RØDBETSALAT', 'Rødbetsalat, Mills'),
  ('S.M.MUSKATNØTT MALT', 'Muskat'),
  ('S.M.RED CURRYPASTE', 'Curry paste'),
  ('S.M.TACO SAUCE HOT', 'Tacolefser/nachos/taco'),
  ('S.M.TACO SPICEMI.3PK', 'Tacolefser/nachos/taco'),
  ('SALAME TRØFFEL', 'Salami, Taga trøffelsalami'),
  ('SALAT CRISPI', 'Crispisalat'),
  ('SALAT CRISPI 150G', 'Crispisalat'),
  ('SALATOST', 'Feta/salatost, Urter/hvitløk'),
  ('SALATOST URTER/HVITL', 'Feta/salatost'),
  ('Siratcha', 'Sriracha'),
  ('SITRONER', 'Sitron'),
  ('SJAMP', 'Sjampinjong, X-tra 250 g'),
  ('SJAMP. X-TRA 250G', 'Hår-/kroppspleie'),
  ('SJOKADE 450G', 'Sjokade'),
  ('SKRELLA MOZZARELLA', 'Mozzarella'),
  ('SMAK SALAMI FELINO', 'Salami'),
  ('SNACK GULROT', 'Snackgulrøtter, 250 g'),
  ('SNACK GULROT 250G', 'Gulrøtter'),
  ('SOMMERKOTELETTER', 'Grillkjøtt/koteletter/ribs'),
  ('SOPPS SPAGETTI FULLK', 'Fullkornsspagetti'),
  ('SPAGH.A LA CAPRI', 'Spaghetti à la Capri, Toro'),
  ('SPRØBAKTE CRISPIES', 'Crispisalat'),
  ('STABBUR-MAKRELL', 'Makrell i tomat, Stabbur'),
  ('STABBUR-MAKRELL 110G', 'Makrell i tomat'),
  ('SUKKER 1KG', 'Sukker'),
  ('SVINEKOTELETTER', 'Svinekoteletter, Marinerte'),
  ('SVINEKOTELETTER MAR.', 'Grillkjøtt/koteletter/ribs'),
  ('SØRL.SPANSK PAPRIKA', 'Chips/snacks'),
  ('SØTPOTET', 'Poteter'),
  ('TACO SAUCE HOT', 'Tacosaus hot, Santa Maria'),
  ('TACO SPICEMI', 'Tacokrydder, Santa Maria 3-pk'),
  ('Tacoktydder', 'Tacokrydder'),
  ('TAGA SALAME TRØFFEL', 'Salami'),
  ('TELYS GULLK.8T 50STK', 'Diverse ikke-mat'),
  ('TINE CRÈME FRAÎCHE', 'Crème fraîche'),
  ('TINE GRESK YOGH', 'Gresk yoghurt, Tine'),
  ('TINE GRESK YOGH.730G', 'Naturell/gresk yoghurt'),
  ('TINE LETTM', 'Lettmelk, Tine 0,5% 1,75 L'),
  ('TINE LETTM.0.5%1.75L', 'Lettmelk'),
  ('TINE LETTMELK 1% 1L', 'Lettmelk'),
  ('TINE LETTRØM.17%300G', 'Lettrømme'),
  ('TINE REVET OST', 'Revet ost'),
  ('TINE YOGHURT NAT', 'Naturell/gresk yoghurt'),
  ('TINE ØKONOMIPAKKE', 'Gulost/Norvegia'),
  ('TOMAT CHERRY', 'Cherrytomater, X-tra'),
  ('TOMAT CHERRY X-TRA', 'Tomater'),
  ('TOMAT PERLE 175G', 'Tomater'),
  ('TOMATSUPPE FULLKORN', 'Tomatsuppe'),
  ('TORO BALI KYLL.GRYTE', 'Toro Bali kyllinggryte'),
  ('TORO BRETAGNESAUS FA', 'Toro Bretagnesaus'),
  ('TORO PIZZAFYLL MEXIC', 'Pizza/pizzatilbehør'),
  ('TORO PIZZAFYLL TO&LØ', 'Pizza/pizzatilbehør'),
  ('TORT.CHIPS', 'Tortillachips, Coop salt'),
  ('TRITAN DRIKKEFLASKE', 'Diverse ikke-mat'),
  ('TRO SPAGH.A LA CAPRI', 'Fullkornsspagetti'),
  ('TUB.LITE', 'Øl, Tuborg Lite'),
  ('TUB.LITE 0.5L BX', 'Øl'),
  ('TUB.LITE 0.5L BX 6PK', 'Øl'),
  ('TURSHORTS EKKERTIND', 'Diverse ikke-mat'),
  ('Tørkepapir', 'Tørkerull'),
  ('VESTL.LEFSESNACK 2PK', 'Tacolefser/nachos/taco'),
  ('WASA RUGSPRØ', 'Rugsprø, Wasa'),
  ('WASA RUGSPRØ 200G', 'Knekkebrød/Rugsprø'),
  ('XTRA CHOCLATE CHIP', 'Søtsaker/is/sjokolade'),
  ('XTRA EGG', 'Egg, Xtra 12-pk'),
  ('XTRA EGG 12PK', 'Egg'),
  ('XTRA HVITL.BAGUETT', 'Hvitløksbaguetter'),
  ('XTRA JASMINRIS 5KG', 'Ris'),
  ('XTRA KJØTTDEIG', 'Kjøttdeig'),
  ('XTRA KJØTTPØLSE', 'Pølser'),
  ('XTRA KOKT SKINK.250G', 'Kokt skinke'),
  ('XTRA LAKSEFILET', 'Laks, Xtra laksefilet 4-pk'),
  ('XTRA LAKSEFILET 4PK', 'Laksefilet'),
  ('XTRA MOZZARELLA 125G', 'Mozzarella'),
  ('XTRA SEIFILET 400G', 'Seifilet'),
  ('YOGH.SKOGSB', 'Yoghurtbeger skogsbær'),
  ('YOGH.SKOGSB.4X150G', 'Yoghurt'),
  ('YOGH.VANILJE', 'Yoghurtbeger vanilje'),
  ('YOGH.VANILJE 4X150G', 'Yoghurt'),
  ('YONCA TOMATPURE', 'Tomatpuré'),
  ('ZALO ULTRA 5DL', 'Vaskemiddel/oppvask'),
  ('¤GJENBRUK HANDLENETT', 'Pose/handlenett'),
  ('¤HANDLENETT EXTRA', 'Pose/handlenett'),
  ('¤LAMBI TOA.PAPIR 24PK', 'Toalettpapir'),
  ('¤ÄNGLAM.COLOR REFILL', 'Vaskemiddel/oppvask'),
  ('ÃM TOMATER FINMOST', 'Finmoste tomater, Änglamark'),
  ('Änglamark PIZZA SAUS', 'Pizzasaus'),
  ('Änglamark SOLSIKKEK.', 'Solsikkekjerner'),
  ('Änglamark TOMATER FINMOST', 'Tomater')
on conflict (from_text) do nothing;
